/*
** Copyright (c) 2018 by Silicon Laboratories
**
** file: si_voice_version.c
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/



char *SiVoiceAPIVersion = "9.2.0";



