#!/bin/bash
# Installing *.lua files from V_variables/value directories to installation directory
nof=${0##*/}
usage() {
	cat <<EOM
Usage: $nof VFILE SRC_DIR INSTALL_DIR

Installing *.lua files from V_variables/value directories to installation directory
	VFILE		Path to variant.sh
	SRC_DIR		Source directory
	INSTALL_DIR	Installation directory

Order of copying:
	V_features are copied first in alphabetical order
	Next, V_SKIN is copied and replaces ones in the installation directory
	Next, V_CUSTOM_FEATURE_PACK is copied and replaces ones in the installation directory
	Finally, V_PRODUCT is copied and replaces ones in the installation directory
EOM

	exit 1
}

VLISTFILE="v_extension_list__.lua"
v_pre_install() {
	local INSTALL_DIR=$1
	cat <<EOF > $INSTALL_DIR/$VLISTFILE
-- generated by $nof
local v_list = {
EOF

}

v_post_install() {
	local INSTALL_DIR=$1
	cat <<EOF >> "$INSTALL_DIR/$VLISTFILE"
}
return v_list
EOF

}

v_install() {
	local SRC_DIR=$1
	local INSTALL_DIR=$2
	local VDIR=$3
	local VVAL=${!VDIR}

	local file_list=
	if [ -n "$VVAL" -a -d "$SRC_DIR/$VDIR/$VVAL" ]; then
		file_list=$(find "$SRC_DIR/$VDIR/$VVAL" -maxdepth 1 -name "*.lua" -type f -printf "%f\n")
		for file in $file_list; do
			case $file in
				extension__.lua)
					install -m 644 "$SRC_DIR/$VDIR/$VVAL/$file" "$INSTALL_DIR/extension__$VDIR.lua"
					cat <<EOF >> "$INSTALL_DIR/$VLISTFILE"
  "extension__$VDIR",
EOF

					;;
				*)
					install -m 644 "$SRC_DIR/$VDIR/$VVAL/$file" "$INSTALL_DIR"
					;;
			esac
		done
	fi
}

if [ $# -lt 3 ]; then
	usage
fi

VFILE=$1
SRC_DIR=$2
INSTALL_DIR=$3

if [ ! -f "$VFILE" ]; then
	echo "Error: VFILE must be the path to variant.sh"
	usage
fi
if [ ! -d "$SRC_DIR" ]; then
	echo "Error: SRC_DIR must be the source directory."
	usage
fi
if [ ! -d "$INSTALL_DIR" ]; then
	echo "Error: INSTALL_DIR must be the installation directory."
	usage
fi

source "$VFILE"
v_pre_install "$INSTALL_DIR"
VDIRS=$(find "$SRC_DIR" -maxdepth 1 -name "V_*" -type d -printf "%f\n")
for VDIR in $VDIRS; do
	case $VDIR in
		V_SKIN|V_CUSTOM_FEATURE_PACK|V_PRODUCT) ;;
		*) v_install "$SRC_DIR" "$INSTALL_DIR" "$VDIR" ;;
	esac
done

# Phobos-94:extension__V_CUSTOM_FEATURE_PACK.lua is excluded from Phobos as it
# conflicts with custom-apn code during detach-reattach. Refer Jira for details
if [[ $V_PRODUCT == "nbn_cfw2131" ]]; then
	VPRIORITY="V_SKIN V_PRODUCT"
else
	VPRIORITY="V_SKIN V_CUSTOM_FEATURE_PACK V_PRODUCT"
fi
for VDIR in $VPRIORITY; do
	v_install "$SRC_DIR" "$INSTALL_DIR" "$VDIR"
done
v_post_install "$INSTALL_DIR"
