#!/bin/sh

# This script starts/stops/restarts WWAN Modem Manager Daemon (wmmd)
# At the moment, it is not placed in any run level, but is called from
# a wmmd.template. So there is no symlink referring to it.

PROG_NAME="wmmd"
PIDFILE="/var/run/$PROG_NAME.pid"

start() {
	echo "wmmd: start $PROG_NAME"
	start-stop-daemon -S -b -m -p $PIDFILE -x "/usr/bin/wmmd_launcher"
	echo "started."
}

get_monotonic_msec() {
	awk '/^now/ {print substr($3, 1, length($3) - 6); exit}' /proc/timer_list
}

stop() {
	# stop daemon
	echo "wmmd: stop $PROG_NAME"
	local PID=$(cat $PIDFILE 2>/dev/null)
	start-stop-daemon -K -q -p $PIDFILE 2> /dev/null

	start=$(get_monotonic_msec)
	while pgrep -P $PID >&/dev/null; do
		sleep 0.1

		cur=$(get_monotonic_msec)
		runtime=$((cur-start))
		if [ $runtime -gt 5 ]; then
			break;
		fi
	done

	if pgrep -P $PID >&/dev/null; then
		start-stop-daemon -K -q -p $PIDFILE -s SIGKILL 2> /dev/null
	fi

	rdb unset service.wmmd.watchdog
	rm -f $PIDFILE

	echo "stopped."
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
