<script language="JavaScript">

// A list of all defined end points. When a new ep is defined, we only need to add it here.
var g_ep_types_list={"1":_("type1"), "2":_("type2"), "3":_("type3"),  "4":_("type4"), "5":_("type5"), "6":_("type6"), 
				"7":_("type7"), "8":_("type8"), "9":_("type9"), "10":_("type10"), \
				"11":_("type11"), "12":_("type12"), "13":_("type13"), "14":_("type14"), "15":_("type15"), "16":_("type16"), "17":_("type17")};

</script>
