/* Copyright 2015, Silicon Labs */
/* Autogenerated file - do not modify */

#include <stdlib.h>
#include "si3217x_BKBT_constants.h"

const char *Ring_preset_options[] =
{
	"RING_MAX_VBAT_PROVISIONING",
	"RING_F20_45VRMS_0VDC_LPR",
	"RING_F20_45VRMS_0VDC_BAL",
	NULL
};

const char *DcFeed_preset_options[] =
{
	"DCFEED_48V_20MA",
	"DCFEED_48V_25MA",
	"DCFEED_PSTN_DET_1",
	"DCFEED_PSTN_DET_2",
	NULL
};

const char *Impedance_preset_options[] =
{
	"ZSYN_600_0_0_30_0",
	"ZSYN_270_750_150_30_0",
	"ZSYN_370_620_310_30_0",
	"ZSYN_220_820_120_30_0",
	"ZSYN_600_0_1000_30_0",
	"ZSYN_200_680_100_30_0",
	"ZSYN_220_820_115_30_0",
	"WB_ZSYN_600_0_0_20_0",
	NULL
};

const char *FSK_preset_options[] =
{
	"DEFAULT_FSK",
	"ETSI_FSK",
	NULL
};

const char *PulseMeter_preset_options[] =
{
	"DEFAULT_PULSE_METERING",
	NULL
};

const char *Tone_preset_options[] =
{
	"TONEGEN_FCC_DIAL",
	"TONEGEN_FCC_BUSY",
	"TONEGEN_FCC_RINGBACK",
	"TONEGEN_FCC_REORDER",
	"TONEGEN_FCC_CONGESTION",
	"TONEGEN_FCC_CAS",
	"TONEGEN_FCC_SAS",
	"TONEGEN_ETSI_DTAS",
	"TONEGEN_1004",
	NULL
};

const char *PCM_preset_options[] =
{
	"PCM_8ULAW",
	"PCM_8ALAW",
	"PCM_16LIN",
	"PCM_16LIN_WB",
	NULL
};

