/*
** Copyright (c) 2016 Silicon Laboratories, Inc.
** 2016-05-10 11:11:58
**
** Si3228x ProSLIC API Configuration Tool Version 4.0.4
** Last Updated in API Release: 8.1.0
** source XML file: si3228x_BRCM_LCCB_SR_constants.xml
**
** Auto generated file from configuration tool.
*/


#ifndef SI3228X_CONSTANTS_H
#define SI3228X_CONSTANTS_H

/** Ringing Presets */
enum {
	AU_RINGING,
	AUS_RINGING,
	BE_RINGING,
	BR_RINGING,
	CHL_RINGING,
	CH_RINGING,
	CZ_RINGING,
	DN_RINGING,
	ETSI_RINGING,
	FI_RINGING,
	FR_RINGING,
	GER_RINGING,
	HU_RINGING,
	IT_RINGING,
	JP_RINGING,
	NE_RINGING,
	NZ_RINGING,
	NA_RINGING,
	PL_RINGING,
	SP_RINGING,
	SE_RINGING,
	NO_RINGING,
	SW_RINGING,
	GR57_RINGING,
	UK_RINGING,
	TW_RINGING,
	IN_RINGING,
	RINGING_LAST_ENUM
};

/** DC_Feed Presets */
enum {
	AU_DC,
	AUS_DC,
	BE_DC,
	BR_DC,
	CHL_DC,
	CH_DC,
	CZ_DC,
	DN_DC,
	ETSI_DC,
	FI_DC,
	FR_DC,
	GER_DC,
	HU_DC,
	IT_DC,
	JP_DC,
	NE_DC,
	NZ_DC,
	NA_DC,
	PL_DC,
	SP_DC,
	SE_DC,
	NO_DC,
	SW_DC,
	GR57_DC,
	UK_DC,
	TW_DC,
	IN_DC,
	DC_FEED_LAST_ENUM
};

/** Impedance Presets */
enum {
	AU_IMPEDANCE,
	AUS_IMPEDANCE,
	BE_IMPEDANCE,
	BR_IMPEDANCE,
	CHL_IMPEDANCE,
	CH_IMPEDANCE,
	CZ_IMPEDANCE,
	DN_IMPEDANCE,
	ETSI_IMPEDANCE,
	FI_IMPEDANCE,
	FR_IMPEDANCE,
	GER_IMPEDANCE,
	HU_IMPEDANCE,
	IT_IMPEDANCE,
	JP_IMPEDANCE,
	NE_IMPEDANCE,
	NZ_IMPEDANCE,
	NA_IMPEDANCE,
	PL_IMPEDANCE,
	SP_IMPEDANCE,
	SE_IMPEDANCE,
	NO_IMPEDANCE,
	SW_IMPEDANCE,
	GR57_IMPEDANCE,
	UK_IMPEDANCE,
	TW_IMPEDANCE,
	IN_IMPEDANCE,
	IMPEDANCE_LAST_ENUM
};

/** FSK Presets */
enum {
	DEFAULT_FSK,
	FSK_LAST_ENUM
};

/** Pulse_Metering Presets */
enum {
	DEFAULT_PULSE_METERING,
	PULSE_METERING_LAST_ENUM
};

/** Tone Presets */
enum {
	DEFAULT_TONE,
	TONE_LAST_ENUM
};

/** PCM Presets */
enum {
	ALAW_NEGATIVEEDGE_PCM,
	ULAW_NEGATIVEEDGE_PCM,
	LINEAR_NEGATIVEEDGE_PCM,
	PCM_LAST_ENUM
};


/** Generic Preset Enumeration */
enum {
    SI3226x_AUSTRALIA,
    SI3226x_AUSTRIA,
    SI3226x_BELGIUM,
    SI3226x_BRAZIL,
    SI3226x_CHILE,
    SI3226x_CHINA,
    SI3226x_CZECH,
    SI3226x_DENMARK,
    SI3226x_ETSI,
    SI3226x_FINLAND,
    SI3226x_FRANCE,
    SI3226x_GERMANY,
    SI3226x_HUNGARY,
    SI3226x_ITALY,
    SI3226x_JAPAN,
    SI3226x_NETHERLANDS,
    SI3226x_NEW_ZEALAND,
    SI3226x_NORTH_AMERICA,
    SI3226x_POLAND,
    SI3226x_SPAIN,
    SI3226x_SWEDEN,
    SI3226x_NORWAY,
    SI3226x_SWITZERLAND,
    SI3226x_TR57,
    SI3226x_UK,
    SI3226x_TAIWAN,
    SI3226x_INDIA,
    SI3226x_LOCALE_MAX
};

#define	INIT_API_PRESET_RINGING	NA_RINGING
#define	INIT_API_PRESET_DC_FEED	NA_DC
#define	INIT_API_PRESET_IMPEDANCE	NA_IMPEDANCE
#define	INIT_API_PRESET_PCM	LINEAR_NEGATIVEEDGE_PCM

#endif

