cat << EOF
# Generated by rdb_watchdog.conf__fsx.sh
# Configuration to add RDB variables that should be monitored for change by RDB watchdog
# Up to 5 RDB variables are allowed to be monitored - reboot forced if they don't change.
EOF
# Note: keeping above short on the device.
# format of following lines is: variable timeout
# variable should be a temporary(not permanent) RDB variable, timeout should be greater than 10 secs.
# e.g.) monitor a sys.watchdog.sysTicks variable and reboot if there is no change of the value for 60 secs
# sys.watchdog.sysTicks 60

# Configuration to add RDB variables that should be monitored their change by RDB watchdog

# monitoring Ethernet controller
if [ "$V_MONITOR_ETHERNET" != "none" ]; then
	echo "monitor.ethernet.watchdog 300"
fi
