#! /bin/sh

set -e

if [ -f /etc/syslog-startup.conf ]; then
	. /etc/syslog-startup.conf
else
	# default: log to 16K shm circular buffer
	SYSLOG_ARGS="-C16"
fi

case "$1" in
  start)
	echo -n "Starting syslogd "
	start-stop-daemon -S -b -n syslogd -a /sbin/syslogd -- -n $SYSLOG_ARGS
	start-stop-daemon -S -b -n klogd -a /sbin/klogd -- -n
	echo "done"
	;;
  stop)
	echo -n "Stopping syslogd "
	start-stop-daemon -K -n klogd
	start-stop-daemon -K -n syslogd
	echo "done"
	;;
  restart)
  	$0 stop
	$0 start
	;;
  *)
	echo "Usage: syslog { start | stop | restart }" >&2
	exit 1
	;;
esac

exit 0
