ProSLIC API: Message Waiting Indicator routines
Message Waiting Indicator routines
ProSLIC API
Functions
int ProSLIC_MWISetV (proslicChanType_ptr hProslic, uInt16 vpk_mag)
Configure optional MWI voltage settings. Default value is 95v.
int ProSLIC_MWIEnable (proslicChanType_ptr hProslic)
Enables message waiting indicator feature.
int ProSLIC_MWIDisable (proslicChanType_ptr hProslic)
Disables message waiting indicator feature.
int ProSLIC_SetMWIState (proslicChanType_ptr hProslic, uInt8 flash_on)
Implements message waiting indicator.
int ProSLIC_MWIRampStart (proslicChanType_ptr pProslic, uInt32 steps, uInt32 onTime, uInt32 offTime)
Intializes message waiting indicator with ramp configurability.
int ProSLIC_MWIRampPoll (proslicChanType_ptr pProslic)
Implements message waiting indicator with ramp between ON and OFF states.
int ProSLIC_MWIRampStop (proslicChanType_ptr pProslic)
Restores ramping message waiting indicator state.
int ProSLIC_GetMWIState (proslicChanType_ptr hProslic)
Read MWI output state.
Detailed Description
Function Documentation
int ProSLIC_GetMWIState (proslicChanType_ptr hProslic)
Read MWI output state.
Message waiting (neon flashing) state read. If MWI feature has not been enabled by calling ProSLIC_SetMWIEnable(), then this function will return RC_MWI_NOT_ENABLED
Note
Proper patch must be loaded for this feature to work properly. Code does not automatically verify that this patch is loaded.
Parameters
[in] hProslic - channel to modify
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_GPIOControl().
int ProSLIC_MWIDisable (proslicChanType_ptr hProslic)
Disables message waiting indicator feature.
Message waiting (neon flashing) disable. Turns off flashing and disabled MWI feature.
Note
Proper patch must be loaded for this feature to work properly. Code does not automatically verify that this patch is loaded.
Parameters
[in] hProslic - channel to modify
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_GPIOControl().
int ProSLIC_MWIEnable (proslicChanType_ptr hProslic)
Enables message waiting indicator feature.
Message waiting (neon flashing) enabled if device is in the onhook state. Otherwise, function will not execute and return RC_MWI_ENABLE_FAIL. This function must be called to ENABLE MWI prior to calling ProSLIC_MWI to toggle the voltage level on TIP-RING.
Note
Proper patch must be loaded for this feature to work properly. Code does not automatically verify that this patch is loaded.
Parameters
[in] hProslic - channel to modify
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_GPIOControl().
int ProSLIC_MWIRampPoll (proslicChanType_ptr pProslic)
Implements message waiting indicator with ramp between ON and OFF states.
Message waiting (neon flashing) polling function. If MWI feature has not been enabled by calling ProSLIC_SetMWIEnable(), then this function will return RC_MWI_NOT_ENABLED
Note
Proper patch must be loaded for this feature to work properly. Code does not automatically verify that this patch is loaded.
Parameters
[in] pProslic - channel to modify
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_GPIOControl().
int ProSLIC_MWIRampStart (proslicChanType_ptr pProslic, uInt32 steps, uInt32 onTime, uInt32 offTime)
Intializes message waiting indicator with ramp configurability.
Message waiting (neon flashing) initialization. If MWI feature has not been enabled by calling ProSLIC_SetMWIEnable(), then this function will return RC_MWI_NOT_ENABLED
Note
Proper patch must be loaded for this feature to work properly. Code does not automatically verify that this patch is loaded.
Parameters
[in] pProslic - channel to modify
[in] steps - number of steps in ramp, tick duration is time of one step
[in] onTime - number of ticks MWI is in the ON state
[in] offTime - number of ticks MWI is in the OFF state
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_GPIOControl().
int ProSLIC_MWIRampStop (proslicChanType_ptr pProslic)
Restores ramping message waiting indicator state.
Message waiting (neon flashing) stop function. If MWI feature has not been enabled by calling ProSLIC_SetMWIEnable(), then this function will return RC_MWI_NOT_ENABLED
Note
Proper patch must be loaded for this feature to work properly. Code does not automatically verify that this patch is loaded.
Parameters
[in] pProslic - channel to modify
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_GPIOControl().
int ProSLIC_MWISetV (proslicChanType_ptr hProslic, uInt16 vpk_mag)
Configure optional MWI voltage settings. Default value is 95v.
Set MWI flashing voltage level (Vpk).
Note
Proper patch must be loaded for this feature to work properly. Code does not automatically verify that this patch is loaded.
Parameters
[in] hProslic - channel to modify
[in] vpk_mag - MWI voltage level (vpk) (no change is made if 0)
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_GPIOControl().
int ProSLIC_SetMWIState (proslicChanType_ptr hProslic, uInt8 flash_on)
Implements message waiting indicator.
Message waiting (neon flashing) state toggling. If MWI feature has not been enabled by calling ProSLIC_SetMWIEnable(), then this function will return RC_MWI_NOT_ENABLED
Note
Proper patch must be loaded for this feature to work properly. Code does not automatically verify that this patch is loaded.
Parameters
[in] hProslic - channel to modify
[in] flash_on - 0 = lamp off, 1 = lamp on.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_GPIOControl().
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page