ProSLIC API: Debug
Debug
ProSLIC API » General configuration
Functions
ramData ProSLIC_ReadRAM (proslicChanType *pProslic, uInt16 addr)
This function allows access to SPI read RAM function pointer from interface.
int ProSLIC_WriteRAM (proslicChanType *pProslic, uInt16 addr, ramData data)
This function allows access to SPI write RAM function pointer from interface.
int ProSLIC_PrintDebugData (proslicChanType *pProslic)
This function dumps to console the register contents of several registers and RAM locations.
int ProSLIC_PrintDebugReg (proslicChanType *pProslic)
This function dumps the registers to the console using whatever I/O method is defined by LOGPRINT.
int ProSLIC_PrintDebugRAM (proslicChanType *pProslic)
This function dumps the RAM to the console using whatever I/O method is defined by LOGPRINT.
Detailed Description
This group of functions enables/disables debug messages as well as dump register contents.
Function Documentation
int ProSLIC_PrintDebugData (proslicChanType * pProslic)
This function dumps to console the register contents of several registers and RAM locations.
Parameters
[in] pProslic - which channel to dump the register contents of.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_ReadMADCScaled().
int ProSLIC_PrintDebugRAM (proslicChanType * pProslic)
This function dumps the RAM to the console using whatever I/O method is defined by LOGPRINT.
Parameters
[in] pProslic - which channel to dump the RAM contents of.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_ReadMADCScaled().
int ProSLIC_PrintDebugReg (proslicChanType * pProslic)
This function dumps the registers to the console using whatever I/O method is defined by LOGPRINT.
Parameters
[in] pProslic - which channel to dump the register contents of.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_ReadMADCScaled().
ramData ProSLIC_ReadRAM (proslicChanType * pProslic, uInt16 addr)
This function allows access to SPI read RAM function pointer from interface.
Parameters
[in] pProslic - pointer to channel structure
[in] addr - address to read
Return values
ramData - RAM contents
Referenced by ProSLIC_destroyTestInObjs(), and ProSLIC_ReadMADCScaled().
int ProSLIC_WriteRAM (proslicChanType * pProslic, uInt16 addr, ramData data)
This function allows access to SPI write RAM function pointer from interface.
Parameters
[in] pProslic - pointer to channel structure
[in] addr - address to write
[in] data to be written
Return values
int - RC_NONE
Referenced by ProSLIC_destroyTestInObjs(), and ProSLIC_ReadMADCScaled().
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page