ProSLIC API: ProSLIC Inward Tests (Test-In)
ProSLIC Inward Tests (Test-In)
ProSLIC API » Diagnostics
Data Structures
struct proslicTestObj
struct proslicPcmLpbkTest
struct proslicDcFeedTest
struct proslicRingingTest
struct proslicBatteryTest
struct proslicAudioTest
struct proslicTestInObjType
Macros
#define MIN_RINGING_SAMPLES 16
#define MAX_RINGING_SAMPLES 255
#define MIN_RINGING_SAMPLE_INTERVAL 1
#define MAX_RINGING_SAMPLE_INTERVAL 10
#define ProSLIC_createTestInObj(X) ProSLIC_createTestInObjs((X),1)
#define ProSLIC_destroyTestInObj ProSLIC_destroyTestInObjs
Typedefs
typedef proslicTestInObjType * proslicTestInObjType_ptr
Enumerations
enum { TSTIN_RESULTS_INVALID, TSTIN_RESULTS_VALID }
enum { PCM_8BIT, PCM_16BIT }
enum { ABORT_LIU_DISABLED, ABORT_LIU_ENABLED }
enum { LCR_CHECK_DISABLED, LCR_CHECK_ENABLED }
enum { RTP_CHECK_DISABLED, RTP_CHECK_ENABLED }
Functions
int ProSLIC_createTestInObjs (proslicTestInObjType_ptr *pTstin, uInt32 num_objs)
Allocate memory and initialize the given structure.
int ProSLIC_destroyTestInObjs (proslicTestInObjType_ptr *pTstin)
Free memory reserved by the given structure.
int ProSLIC_testInPCMLpbkEnable (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Enable PCM loopback.
int ProSLIC_testInPCMLpbkDisable (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Disable PCM loopback.
int ProSLIC_testInDCFeed (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
DC Feed Test - the pTstin->dcFeedTest contains control, limits and test result information.
int ProSLIC_testInRinging (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Ringing and Ringtrip Test.
int ProSLIC_testInBattery (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Battery Test - pTstin contains both the configuration data and test results. See **pTstin->batteryTest.testResult - Pass/Fail result.
int ProSLIC_testInAudio (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Audio level inward test. pTstin->audioTest contains all control, limits and results.
int ProSLIC_testInPcmLpbkSetup (proslicTestInObjType *pTstin, proslicPcmLpbkTest *pcmLpbkTest)
Initialize/Enable PCM Loopback Test. Links test config/limits to inward test data structure.
int ProSLIC_testInDcFeedSetup (proslicTestInObjType *pTstin, proslicDcFeedTest *dcFeedTest)
Initialize/Enable DC Feed Test. Links test config/limits to inward test data structure.
int ProSLIC_testInRingingSetup (proslicTestInObjType *pTstin, proslicRingingTest *ringingTest)
Initialize/Enable Ringing Test. Links test config/limits to inward test data structure.
int ProSLIC_testInBatterySetup (proslicTestInObjType *pTstin, proslicBatteryTest *batteryTest)
Initialize/Enable Battery Test. Links test config/limits to inward test data structure.
int ProSLIC_testInAudioSetup (proslicTestInObjType *pTstin, proslicAudioTest *audioTest)
Initialize/Enable Audio Test. Links test config/limits to inward test data structure.
int ProSLIC_testInPrintLimits (proslicChanType *pProslic, proslicTestInObjType *pTstin)
Debug utility to log presently loaded test limits.
int ProSLIC_testLoadTest (SiVoiceChanType_ptr pProslic, BOOLEAN is_testStart, uint32_t timeDelayMsec)
Provide a simulated offhook using the ProSLIC test load. You would call this function twice: once to enable the simulated test load (is_testStart = TRUE) and check if the upper layer correctly detected the hook state change and possibly pass some audio. After you have completed this test/check, you would call the same function again to restore the system to normal state (is_testStart = FALSE).
Detailed Description
This section documents functions and data structures related to the ProSLIC/FXS inward test implementations.
Macro Definition Documentation
#define MAX_RINGING_SAMPLE_INTERVAL 10
Maximum sample interval for measuring ring amplitude
Definition at line 37 of file proslic_tstin.h.
Referenced by ProSLIC_destroyTestInObjs().
#define MAX_RINGING_SAMPLES 255
Maximum number of ringing samples for measuring ring amplitude
Definition at line 35 of file proslic_tstin.h.
Referenced by ProSLIC_destroyTestInObjs().
#define MIN_RINGING_SAMPLE_INTERVAL 1
Minimum sample interval for measuring ring amplitude
Definition at line 36 of file proslic_tstin.h.
Referenced by ProSLIC_destroyTestInObjs().
#define MIN_RINGING_SAMPLES 16
Minimum number of ringing samples for measuring ring amplitude
Definition at line 34 of file proslic_tstin.h.
Enumeration Type Documentation
anonymous enum
Check for loop closure option
Definition at line 69 of file proslic_tstin.h.
anonymous enum
Check for ringtrip option
Definition at line 78 of file proslic_tstin.h.
anonymous enum
Test-In results status
Definition at line 42 of file proslic_tstin.h.
anonymous enum
PCM format options
Definition at line 51 of file proslic_tstin.h.
anonymous enum
Abort if Line-in-use option
Definition at line 60 of file proslic_tstin.h.
Function Documentation
int ProSLIC_createTestInObjs (proslicTestInObjType_ptr * pTstin, uInt32 num_objs)
Allocate memory and initialize the given structure.
Parameters
[in,out] *pTstin - the structure to initialize
[in] num_objs - number of Testin structures to allocate.
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_DestroyTestInObjs
Definition at line 627 of file proslic_tstin.c.
References RC_NO_MEM, RC_NONE, and RC_UNSUPPORTED_FEATURE.
int ProSLIC_destroyTestInObjs (proslicTestInObjType_ptr * pTstin)
Free memory reserved by the given structure.
Parameters
[in,out] *pTstin - the structure to initialize
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 648 of file proslic_tstin.c.
References proslicDcFeedTest::abortIfLineInUse, proslicRingingTest::abortIfLineInUse, proslicAudioTest::abortIfLineInUse, proslicDcFeedTest::altLcrOffThresh, proslicDcFeedTest::altLcrOnThresh, proslicDcFeedTest::applyLcrThresh, proslicDcFeedTest::dcfeedIlongOffhook, proslicDcFeedTest::dcfeedIlongOnhook, proslicDcFeedTest::dcfeedIloopOffhook, proslicDcFeedTest::dcfeedIloopOnhook, proslicDcFeedTest::dcfeedIringOffhook, proslicDcFeedTest::dcfeedIringOnhook, proslicDcFeedTest::dcfeedItipOffhook, proslicDcFeedTest::dcfeedItipOnhook, proslicDcFeedTest::dcfeedVbatOffhook, proslicDcFeedTest::dcfeedVbatOnhook, proslicDcFeedTest::dcfeedVloopOffhook, proslicDcFeedTest::dcfeedVloopOnhook, proslicDcFeedTest::dcfeedVringOffhook, proslicDcFeedTest::dcfeedVringOnhook, proslicDcFeedTest::dcfeedVtipOffhook, proslicDcFeedTest::dcfeedVtipOnhook, proslicMonitorType::ilong, proslicMonitorType::iring, proslicMonitorType::itip, proslicMonitorType::itr, proslicDcFeedTest::lcrStatus, LF_FWD_ACTIVE, LF_FWD_OHT, LF_OPEN, LF_RINGING, MAX_RINGING_SAMPLE_INTERVAL, MAX_RINGING_SAMPLES, MIN_RINGING_SAMPLE_INTERVAL, proslicRingingTest::numSamples, proslicPcmLpbkTest::pcm8BitLinear, proslicPcmLpbkTest::pcmLpbkEnabled, proslicPcmLpbkTest::pcmModeSave, ProSLIC_DCFeedSetupCfg(), ProSLIC_LineMonitor(), ProSLIC_ReadMADCScaled(), ProSLIC_ReadRAM(), ProSLIC_SetLinefeedStatus(), ProSLIC_testInAudio(), ProSLIC_testInBattery(), ProSLIC_testInDCFeed(), ProSLIC_testInPCMLpbkDisable(), ProSLIC_testInPCMLpbkEnable(), ProSLIC_testInRinging(), ProSLIC_WriteRAM(), RC_LINE_IN_USE, RC_NONE, RC_RING_START_FAIL, RC_TEST_DISABLED, RC_UNSUPPORTED_FEATURE, proslicRingingTest::ringingVac, proslicRingingTest::ringingVdc, proslicRingingTest::ringtripTestEnable, proslicRingingTest::rtpStatus, proslicAudioTest::rxGain, proslicRingingTest::sampleInterval, proslicDcFeedTest::testDataValid, proslicRingingTest::testDataValid, proslicBatteryTest::testDataValid, proslicAudioTest::testDataValid, proslicPcmLpbkTest::testEnable, proslicDcFeedTest::testEnable, proslicRingingTest::testEnable, proslicBatteryTest::testEnable, proslicAudioTest::testEnable, proslicDcFeedTest::testResult, proslicRingingTest::testResult, proslicBatteryTest::testResult, proslicAudioTest::testResult, proslicAudioTest::txGain, proslicTestObj::value, proslicBatteryTest::vbat, proslicMonitorType::vbat, proslicMonitorType::vring, proslicMonitorType::vtip, proslicMonitorType::vtr, and proslicAudioTest::zerodBm_mVpk.
int ProSLIC_testInAudio (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Audio level inward test. pTstin->audioTest contains all control, limits and results.
Parameters
[in] pProslic - channel data structure
[in,out] pTstin - all control, limits, and results
Return values
int - error from errorCodeType
RC_TEST_PASSED indicates test completed and passed
RC_TEST_FAILED indicates test completed and failed
RC_UNSUPPORTED_FEATURE indicates feature not supported on this device
RC_TEST_DISABLED indicates test has not been initialized/enabled
RC_LINE_IN_USE indicates LCS already set
Referenced by ProSLIC_destroyTestInObjs().
int ProSLIC_testInAudioSetup (proslicTestInObjType * pTstin, proslicAudioTest * audioTest)
Initialize/Enable Audio Test. Links test config/limits to inward test data structure.
Parameters
[in,out] pTstin->audioTest - all control, limits, and results
[in] audioTest - test config and limits to link to pTstin->audioTest
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 1354 of file proslic_tstin.c.
References RC_NONE, and proslicAudioTest::testEnable.
int ProSLIC_testInBattery (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Battery Test - pTstin contains both the configuration data and test results. See **pTstin->batteryTest.testResult - Pass/Fail result.
Parameters
[in] pProslic - channel data structure
[in,out] pTstin - configuration and test results
Return values
int - error from errorCodeType
RC_TEST_PASSED indicates test completed and passed
RC_TEST_FAILED indicates test completed and failed
RC_UNSUPPORTED_FEATURE indicates feature not supported on this device
RC_TEST_DISABLED indicates test has not been initialized/enabled
Referenced by ProSLIC_destroyTestInObjs().
int ProSLIC_testInBatterySetup (proslicTestInObjType * pTstin, proslicBatteryTest * batteryTest)
Initialize/Enable Battery Test. Links test config/limits to inward test data structure.
Parameters
[in,out] pTstin->batteryTest - all control, limits, and results
[in] batteryTest - test config and limits to link to pTstin->batteryTest
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 1341 of file proslic_tstin.c.
References RC_NONE, and proslicBatteryTest::testEnable.
int ProSLIC_testInDCFeed (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
DC Feed Test - the pTstin->dcFeedTest contains control, limits and test result information.
Parameters
[in] pProslic - channel data structure
[in,out] pTstin - all control, limits, and results
Return values
int - error from errorCodeType
RC_TEST_PASSED indicates test completed and passed
RC_TEST_FAILED indicates test completed and failed
RC_UNSUPPORTED_FEATURE indicates feature not supported on this device
RC_TEST_DISABLED indicates test has not been initialized/enabled
RC_LINE_IN_USE indicates LCS already set
Referenced by ProSLIC_destroyTestInObjs().
int ProSLIC_testInDcFeedSetup (proslicTestInObjType * pTstin, proslicDcFeedTest * dcFeedTest)
Initialize/Enable DC Feed Test. Links test config/limits to inward test data structure.
Parameters
[in,out] pTstin->dcFeedTest - all control, limits, and results
[in] dcFeedTest - test config and limits to link to pTstin->dcFeedTest
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 1318 of file proslic_tstin.c.
References RC_NONE, and proslicDcFeedTest::testEnable.
int ProSLIC_testInPCMLpbkDisable (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Disable PCM loopback.
Parameters
[in] pProslic - channel data structure
[in,out] pTstin - all control, limits, and results
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_destroyTestInObjs().
int ProSLIC_testInPCMLpbkEnable (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Enable PCM loopback.
Parameters
[in] pProslic - channel data structure
[in,out] pTstin - all control, limits, and results
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_destroyTestInObjs().
int ProSLIC_testInPcmLpbkSetup (proslicTestInObjType * pTstin, proslicPcmLpbkTest * pcmLpbkTest)
Initialize/Enable PCM Loopback Test. Links test config/limits to inward test data structure.
Parameters
[in,out] pTstin->pcmLpbkTest - all control, limits, and results
[in] pcmLpbkTest - test config and limits to link to pTstin->pcmLpbkTest
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 1307 of file proslic_tstin.c.
References RC_NONE, and proslicPcmLpbkTest::testEnable.
int ProSLIC_testInPrintLimits (proslicChanType * pProslic, proslicTestInObjType * pTstin)
Debug utility to log presently loaded test limits.
Parameters
[in] pProslic - channel data structure
[in] pTstin - inward test data structure
Return values
int - error from errorCodeType
RC_NONE indicates no error.
RC_UNSUPPORTED_FEATURE indicates feature not supported on this device
Definition at line 1367 of file proslic_tstin.c.
References proslicDcFeedTest::dcfeedIlongOffhook, proslicDcFeedTest::dcfeedIlongOnhook, proslicDcFeedTest::dcfeedIloopOffhook, proslicDcFeedTest::dcfeedIloopOnhook, proslicDcFeedTest::dcfeedIringOffhook, proslicDcFeedTest::dcfeedIringOnhook, proslicDcFeedTest::dcfeedItipOffhook, proslicDcFeedTest::dcfeedItipOnhook, proslicDcFeedTest::dcfeedVbatOffhook, proslicDcFeedTest::dcfeedVbatOnhook, proslicDcFeedTest::dcfeedVloopOffhook, proslicDcFeedTest::dcfeedVloopOnhook, proslicDcFeedTest::dcfeedVringOffhook, proslicDcFeedTest::dcfeedVringOnhook, proslicDcFeedTest::dcfeedVtipOffhook, proslicDcFeedTest::dcfeedVtipOnhook, proslicTestObj::lowerLimit, RC_NONE, RC_UNSUPPORTED_FEATURE, proslicRingingTest::ringingVac, proslicRingingTest::ringingVdc, proslicAudioTest::rxGain, proslicAudioTest::txGain, proslicTestObj::upperLimit, and proslicBatteryTest::vbat.
int ProSLIC_testInRinging (proslicChanType_ptr pProslic, proslicTestInObjType_ptr pTstin)
Ringing and Ringtrip Test.
Parameters
[in] pProslic - channel data structure
[in,out] pTstin - all control, limits, and results
Return values
int - error from errorCodeType
RC_TEST_PASSED indicates test completed and passed
RC_TEST_FAILED indicates test completed and failed
RC_UNSUPPORTED_FEATURE indicates feature not supported on this device
RC_TEST_DISABLED indicates test has not been initialized/enabled
RC_LINE_IN_USE indicates LCS already set
Referenced by ProSLIC_destroyTestInObjs().
int ProSLIC_testInRingingSetup (proslicTestInObjType * pTstin, proslicRingingTest * ringingTest)
Initialize/Enable Ringing Test. Links test config/limits to inward test data structure.
Parameters
[in,out] pTstin->ringingTest - all control, limits, and results
[in] ringingTest - test config and limits to link to pTstin->ringingTest
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 1329 of file proslic_tstin.c.
References RC_NONE, and proslicRingingTest::testEnable.
int ProSLIC_testLoadTest (SiVoiceChanType_ptr pProslic, BOOLEAN is_testStart, uint32_t timeDelayMsec)
Provide a simulated offhook using the ProSLIC test load. You would call this function twice: once to enable the simulated test load (is_testStart = TRUE) and check if the upper layer correctly detected the hook state change and possibly pass some audio. After you have completed this test/check, you would call the same function again to restore the system to normal state (is_testStart = FALSE).
Note
This test can only be executed one at a time. Running this on multiple channels that have different DC Feed and digital control settings will cause problems. If the all the channels have the same settings, this restriction can be loosened.
Parameters
[in] pProslic - channel data structure
[in] is_testStart - is the the start or end of test.
[in] timeDelayMsec - how may mSec to delay prior to returning from the function.
Return values
int - error from errorCodeType
RC_NONE indicates no error.
RC_UNSUPPORTED_FEATURE indicates feature not supported on this device
Definition at line 1510 of file proslic_tstin.c.
References SiVoiceChanType::channel, LF_FWD_ACTIVE, LF_OPEN, ProSLIC_DCFeedSetupCfg(), ProSLIC_SetLinefeedStatus(), RC_LINE_IN_USE, RC_NONE, and RC_UNSUPPORTED_FEATURE.
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page