ProSLIC API: Gain control
Gain control
ProSLIC API » Audio » Audio control/configuration
Data Structures
struct ProSLIC_audioGain_Cfg
Enumerations
enum { TXACGAIN_SEL = 0, RXACGAIN_SEL = 1 }
Functions
int ProSLIC_TXAudioGainSetup (proslicChanType_ptr hProslic, int preset)
Sets the TX audio gain (toward the network). This funcion DOES NOT actually calculate the values for the preset. To dynamically calculate the values, you would need to call ProSLIC_dbgSetTXGain .
int ProSLIC_TXAudioGainScale (proslicChanType_ptr hProslic, int preset, uInt32 pga_scale, uInt32 eq_scale)
Adjusts gain of TX audio path by scaling the PGA and Equalizer coefficients by the supplied values.
int ProSLIC_RXAudioGainSetup (proslicChanType_ptr hProslic, int preset)
Configures the RX audio gain (toward the telephone). This function DOES NOT actually calculate the values for the preset. To dynamically calculate the values, you would need to call ProSLIC_dbgSetRXGain .
int ProSLIC_RXAudioGainScale (proslicChanType_ptr hProslic, int preset, uInt32 pga_scale, uInt32 eq_scale)
Adjusts gain of RX audio path by scaling the PGA and Equalizer coefficients by the supplied values.
int ProSLIC_AudioGainSetup (proslicChanType_ptr hProslic, int32 rxgain, int32 txgain, int preset)
Configures and sets the audio gains - for both RX (toward the phone) and the TX (toward the network). Unlike the ProSLIC_RXAudioGainSetup and ProSLIC_TXAudioGainSetup this does both the calculations and then configures the given channel in one step. It is assumed that the preset gain array is at least 2 elements in size.
int ProSLIC_dbgSetRXGain (proslicChanType *pProslic, int32 gain, int impedance_preset, int audio_gain_preset)
This function calculates the preset values for the RX audio (toward the telephone) - it does NOT set the actual register values. For that, please use ProSLIC_RXAudioGainSetup .
int ProSLIC_dbgSetTXGain (proslicChanType *pProslic, int32 gain, int impedance_preset, int audio_gain_preset)
This function calculates the preset values for the TX audio (toward the network) - it does NOT set the actual register values. For that, please use ProSLIC_TXAudioGainSetup .
Detailed Description
Path Selector
Function Documentation
int ProSLIC_AudioGainSetup (proslicChanType_ptr hProslic, int32 rxgain, int32 txgain, int preset)
Configures and sets the audio gains - for both RX (toward the phone) and the TX (toward the network). Unlike the ProSLIC_RXAudioGainSetup and ProSLIC_TXAudioGainSetup this does both the calculations and then configures the given channel in one step. It is assumed that the preset gain array is at least 2 elements in size.
Parameters
[in] hProslic - which channel to configure
[in] rxgain - what is the gain/loss of the RX transmit path in 1 dB units (negative = attenuation)
[in] txgain - what is the gain/loss of the TX transmit path in 1 dB units (negative = attenuation)
[in] preset - what is the impedance preset value
Return values
int - error from errorCodeType RC_NONE indicates no error.
The following code * fragment will set the RX audio gain to -1 dB snd TX audio gain to -5 dB:
 ProSLIC_AudioGain(myChannel, -1, -5,  MY_IMPEDENCE);
See also
ProSLIC_TXAudioGainSetup ProSLIC_dbgSetRXGain ProSLIC_dbgSetRXGain ProSLIC_dbgSetTXGain
Definition at line 1498 of file proslic.c.
References ProSLIC_dbgSetRXGain(), ProSLIC_dbgSetTXGain(), ProSLIC_RXAudioGainSetup(), ProSLIC_TXAudioGainSetup(), and RC_NONE.
int ProSLIC_dbgSetRXGain (proslicChanType * pProslic, int32 gain, int impedance_preset, int audio_gain_preset)
This function calculates the preset values for the RX audio (toward the telephone) - it does NOT set the actual register values. For that, please use ProSLIC_RXAudioGainSetup .
Parameters
[in] pProslic - which channel to configure
[in] gain - gain to set the preset values to.
[in] impedance_preset - impedence preset in the constants file.
[in] audio_gain_preset - index to the audio gain preset to store the value.
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_RXAudioGainSetup ProSLIC_AudioGainSetup ProSLIC_dbgSetTXGain
Definition at line 3611 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, and RC_COMPLETE_NO_ERR.
Referenced by ProSLIC_AudioGainSetup().
int ProSLIC_dbgSetTXGain (proslicChanType * pProslic, int32 gain, int impedance_preset, int audio_gain_preset)
This function calculates the preset values for the TX audio (toward the network) - it does NOT set the actual register values. For that, please use ProSLIC_TXAudioGainSetup .
Parameters
[in] pProslic - which channel to configure
[in] gain - gain to set the preset values to.
[in] impedance_preset - impedance preset in the constants file.
[in] audio_gain_preset - index to the audio gain preset to store the value.
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_TXAudioGainSetup ProSLIC_AudioGainSetup ProSLIC_dbgSetRXGain
Definition at line 3664 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, ProSLIC_LineMonitor(), and RC_COMPLETE_NO_ERR.
Referenced by ProSLIC_AudioGainSetup().
int ProSLIC_RXAudioGainScale (proslicChanType_ptr hProslic, int preset, uInt32 pga_scale, uInt32 eq_scale)
Adjusts gain of RX audio path by scaling the PGA and Equalizer coefficients by the supplied values.
Parameters
[in] hProslic - which channel to configure
[in] preset - which preset to use (this may be from the constants file)
[in] pga_scale - scale factor which pga coefficients are to be multiplied
[in] eq_scale - scale factor which equalizer coefficients are to be multiplied
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
This function can be used in lieu of ProSLIC_dbgSetRXGain to dynamically change the audio gain when gain steps of 0.1dB do not suffice, or if an attenuation
30dB is required.
The following code * fragment will scale the TX audio gain by a factor of (0.707)*(0.500)
 uInt32  pga_gain_scale = 707;
 uInt32  eq_gain_scale  = 500;
 ProSLIC_RXAudioGainScale(pProslic,DEFAULT_PRESET,pga_gain_scale,eq_gain_scale);
See also
ProSLIC_TXAudioGainScale
Definition at line 1441 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, and RC_COMPLETE_NO_ERR.
int ProSLIC_RXAudioGainSetup (proslicChanType_ptr hProslic, int preset)
Configures the RX audio gain (toward the telephone). This function DOES NOT actually calculate the values for the preset. To dynamically calculate the values, you would need to call ProSLIC_dbgSetRXGain .
Parameters
[in] hProslic - which channel to configure
[in] preset - which preset to use (this may be from the constants file)
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
One can use this in conjunction with ProSLIC_dbgSetRXGain to dynamically change the audio gain. It is important to have the presets of both routines match.
The following code * fragment will set the RX audio gain to -1 dB:
 ProSLIC_dbgSetRXGain(myChannel, -1, MY_IMPEDENCE,0);
 ProSLIC_RXAudioGainSetup(myChannel,0);
See also
ProSLIC_TXAudioGainSetup ProSLIC_dbgSetRXGain ProSLIC_AudioGainSetup
Definition at line 1326 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, and RC_COMPLETE_NO_ERR.
Referenced by ProSLIC_AudioGainSetup().
int ProSLIC_TXAudioGainScale (proslicChanType_ptr hProslic, int preset, uInt32 pga_scale, uInt32 eq_scale)
Adjusts gain of TX audio path by scaling the PGA and Equalizer coefficients by the supplied values.
Parameters
[in] hProslic - which channel to configure
[in] preset - which preset to use (this may be from the constants file)
[in] pga_scale - scale factor which pga coefficients are to be multiplied
[in] eq_scale - scale factor which equalizer coefficients are to be multiplied
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
This function can be used in lieu of ProSLIC_dbgSetTXGain to dynamically change the audio gain when gain steps of 0.1dB do not suffice, or if an attenuation
30dB is required.
The following code * fragment will scale the TX audio gain by a factor of (0.707)*(0.500)
 uInt32  pga_gain_scale = 707;
 uInt32  eq_gain_scale  = 500;
 ProSLIC_TXAudioGainScale(pProslic,DEFAULT_PRESET,pga_gain_scale,eq_gain_scale);
See also
ProSLIC_RXAudioGainScale
Definition at line 1383 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, and RC_COMPLETE_NO_ERR.
int ProSLIC_TXAudioGainSetup (proslicChanType_ptr hProslic, int preset)
Sets the TX audio gain (toward the network). This funcion DOES NOT actually calculate the values for the preset. To dynamically calculate the values, you would need to call ProSLIC_dbgSetTXGain .
Parameters
[in] hProslic - which channel to configure
[in] preset - which preset to use (this may be from the constants file)
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
One can use this in conjunction with ProSLIC_dbgSetTXGain to dynamically change the audio gain. It is important to have the presets of both routines match.
The following code * fragment will set the TX audio gain to -5 dB:
 ProSLIC_dbgSetTXGain(myChannel, -5, MY_IMPEDENCE,0);
 ProSLIC_TXAudioGainSetup(myChannel,0);
See also
ProSLIC_RXAudioGainSetup ProSLIC_dbgSetTXGain ProSLIC_AudioGainSetup
Definition at line 1270 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, and RC_COMPLETE_NO_ERR.
Referenced by ProSLIC_AudioGainSetup().
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page