ProSLIC API: GPIO Control
GPIO Control
ProSLIC API » General configuration
Functions
int ProSLIC_GPIOSetup (proslicChanType_ptr hProslic)
This function configures the ProSLIC GPIOs by loading a gpio preset that was set in the configuration tool.
int ProSLIC_GPIOControl (proslicChanType_ptr hProslic, uInt8 *pGpioData, uInt8 read)
This function controls the GPIOs of the ProSLIC.
Detailed Description
This group of functions configure, read and write the GPIO status pins.
Function Documentation
int ProSLIC_GPIOControl (proslicChanType_ptr hProslic, uInt8 * pGpioData, uInt8 read)
This function controls the GPIOs of the ProSLIC.
Parameters
[in] hProslic - which channel to modify
[in,out] pGpioData - pointer to GPIO status (typically 1 byte)
[in] read - 1 = Read the status, 0 = write the status
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_GPIOSetup
Definition at line 2181 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, LF_FWD_ACTIVE, LF_RINGING, PROSLIC, ProSLIC_GetMWIState(), ProSLIC_MWIDisable(), ProSLIC_MWIEnable(), ProSLIC_MWIRampPoll(), ProSLIC_MWIRampStart(), ProSLIC_MWIRampStop(), ProSLIC_MWISetV(), PROSLIC_ONHOOK, ProSLIC_ReadHookStatus(), ProSLIC_SetLinefeedStatus(), ProSLIC_SetMWIState(), RC_COMPLETE_NO_ERR, RC_MWI_ENABLE_FAIL, RC_NONE, SI3217X, SI3218X, SI3219X, SI3226X, and SI3228X.
int ProSLIC_GPIOSetup (proslicChanType_ptr hProslic)
This function configures the ProSLIC GPIOs by loading a gpio preset that was set in the configuration tool.
Parameters
[in] hProslic - which channel to configure the GPIO pins.
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_GPIOControl
Definition at line 1646 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, and RC_COMPLETE_NO_ERR.
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page