ProSLIC API: LB Calibration
LB Calibration
ProSLIC API
Functions
int ProSLIC_LBCal (proslicChanType_ptr *pProslic, int size)
Run canned longitudinal balance calibration.
int ProSLIC_GetLBCalResult (proslicChanType *pProslic, int32 *result1, int32 *result2, int32 *result3, int32 *result4)
This function returns the coefficient results of the last LB calibration.
int ProSLIC_LoadPreviousLBCal (proslicChanType *pProslic, int32 result1, int32 result2, int32 result3, int32 result4)
This function loads previously stored LB calibration results to the appropriate ProSLIC RAM locations.
int ProSLIC_GetLBCalResultPacked (proslicChanType *pProslic, int32 *result)
This function returns the results of the last LB calibration packed into single int32.
int ProSLIC_LoadPreviousLBCalPacked (proslicChanType *pProslic, int32 *result)
This function loads previously stored LB calibration results that are in the packed format.
Detailed Description
Function Documentation
int ProSLIC_GetLBCalResult (proslicChanType * pProslic, int32 * result1, int32 * result2, int32 * result3, int32 * result4)
This function returns the coefficient results of the last LB calibration.
Parameters
[in] pProslic - which channel to retrieve the values from.
[out] result1 - results read from the last calibration
[out] result2 - results read from the last calibration
[out] result3 - results read from the last calibration
[out] result4 - results read from the last calibration
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_LBCal ProSLIC_LoadPreviousLBCal ProSLIC_LoadPreviousLBCalPacked ProSLIC_LBCal ProSLIC_GetLBCalResultPacked
Definition at line 3357 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelType, PROSLIC, and RC_NONE.
Referenced by ProSLIC_GetLBCalResultPacked().
int ProSLIC_GetLBCalResultPacked (proslicChanType * pProslic, int32 * result)
This function returns the results of the last LB calibration packed into single int32.
Parameters
[in] pProslic - which channel to retrieve the values from.
[out] result - results - where to store the value
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_LBCal ProSLIC_LoadPreviousLBCal ProSLIC_LoadPreviousLBCalPacked ProSLIC_LBCal
Definition at line 3376 of file proslic.c.
References SiVoiceChanType::channelType, PROSLIC, ProSLIC_GetLBCalResult(), and RC_NONE.
int ProSLIC_LBCal (proslicChanType_ptr * pProslic, int size)
Run canned longitudinal balance calibration.
Parameters
[in] pProslic - start channel to start from for calibration.
[in] size - number of channels to calibrate
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
Use the ProSLIC_Init function to perform all calibrations except Longitudinal Balance (LB). Use the ProSLIC_LBCal function to perform LB calibration. LB Calibration typically needs to execute LB calibration once per system setup without a load connected. The LB calibration results can be stored in non-volatile storage (flash, eeprom) and retrieved during your normal ProSLIC initialization.
See also
ProSLIC_GetLBCalResult ProSLIC_LoadPreviousLBCal ProSLIC_LoadPreviousLBCalPacked ProSLIC_GetLBCalResultPacked
Definition at line 3295 of file proslic.c.
References SiVoiceChanType::error, LF_FWD_ACTIVE, LF_OPEN, PROSLIC, ProSLIC_SetLinefeedStatus(), ProSLIC_SetPowersaveMode(), PWRSAVE_DISABLE, and RC_NONE.
int ProSLIC_LoadPreviousLBCal (proslicChanType * pProslic, int32 result1, int32 result2, int32 result3, int32 result4)
This function loads previously stored LB calibration results to the appropriate ProSLIC RAM locations.
Parameters
[in] pProslic - which channel to program the values
[in] result1 - values to be written
[in] result2 - values to be written
[in] result3 - values to be written
[in] result4 - values to be written
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_LBCal ProSLIC_LoadPreviousLBCalPacked ProSLIC_LBCal ProSLIC_GetLBCalResult ProSLIC_GetLBCalResultPacked
Definition at line 3407 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelType, PROSLIC, and RC_NONE.
Referenced by ProSLIC_LoadPreviousLBCalPacked().
int ProSLIC_LoadPreviousLBCalPacked (proslicChanType * pProslic, int32 * result)
This function loads previously stored LB calibration results that are in the packed format.
Parameters
[in] pProslic - which channel to retrieve the values from.
[in] result - results read from ProSLIC_GetLBCalResultPacked
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_LBCal ProSLIC_LoadPreviousLBCal ProSLIC_LBCal ProSLIC_GetLBCalResultPacked
Definition at line 3436 of file proslic.c.
References SiVoiceChanType::channelType, PROSLIC, and ProSLIC_LoadPreviousLBCal().
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page