ProSLIC API: Diagnostics
Diagnostics
ProSLIC API
Modules
PSTN Check
ProSLIC Inward Tests (Test-In)
Data Structures
struct proslicTestStateType
Functions
int ProSLIC_LineMonitor (proslicChanType_ptr pProslic, proslicMonitorType *monitor)
This function allows one to monitor the instantaneous voltage and loop current values seen on tip/ring.
int32 ProSLIC_ReadMADCScaled (proslicChanType_ptr pProslic, uInt16 addr, int32 scale)
This function reads the MADC a scaled value.
int ProSLIC_VerifyControlInterface (proslicChanType_ptr pProslic)
This function can be used to verify that the SPI interface is functioning properly by performing a series of read back tests. This test DOES modify certain registers, so a reinitialization will be required. This test is recommended only for development use.
Detailed Description
The functions in this group allow one to monitor the line state for abnormal situations.
Function Documentation
int ProSLIC_LineMonitor (proslicChanType_ptr pProslic, proslicMonitorType * monitor)
This function allows one to monitor the instantaneous voltage and loop current values seen on tip/ring.
Parameters
[in] pProslic - which channel should the data be collected from
[in,out] *monitor - the data collected
Return values
int - error from errorCodeType RC_NONE indicates no error.
Referenced by ProSLIC_dbgSetTXGain(), and ProSLIC_destroyTestInObjs().
int32 ProSLIC_ReadMADCScaled (proslicChanType_ptr pProslic, uInt16 addr, int32 scale)
This function reads the MADC a scaled value.
Parameters
[in] pProslic - which channel should the data be collected from
[in] addr - address to read from (MADC_ILOOP, MADC_ITIP, etc).
[in] scale - scale to use (0 = determine based upon MADC address)
Return values
int32 - scaled value requested or -1 if not supported.
Definition at line 114 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, DAA, SiVoiceChanType::deviceId, PROSLIC, ProSLIC_PrintDebugData(), ProSLIC_PrintDebugRAM(), ProSLIC_PrintDebugReg(), ProSLIC_ReadRAM(), ProSLIC_WriteRAM(), RC_NONE, and UNKNOWN.
Referenced by ProSLIC_destroyTestInObjs().
int ProSLIC_VerifyControlInterface (proslicChanType_ptr pProslic)
This function can be used to verify that the SPI interface is functioning properly by performing a series of read back tests. This test DOES modify certain registers, so a reinitialization will be required. This test is recommended only for development use.
Parameters
[in] pProslic - This should point to the channel that is to be verified.
Return values
int - error from errorCodeType RC_NONE indicates no error amd will typically return back RC_SPI_FAIL if a SPI failure occured.
Definition at line 333 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::error, PROSLIC, ProSLIC_Init_MultiBOM(), RC_CHANNEL_TYPE_ERR, RC_COMPLETE_NO_ERR, RC_NONE, and RC_SPI_FAIL.
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page