ProSLIC API: PSTN Check
PSTN Check
ProSLIC API » Diagnostics
Data Structures
struct proslicPSTNCheckObjType
struct proslicDiffPSTNCheckObjType
Macros
#define MAX_ILONG_SAMPLES 32
#define MAX_PSTN_SAMPLES 16
#define ProSLIC_CreatePSTNCheckObj(PTRPTR) ProSLIC_CreatePSTNCheckObjs((PTRPTR), 1)
#define ProSLIC_CreateDiffPSTNCheckObj(PTRPTR) ProSLIC_CreateDiffPSTNCheckObjs((PTRPTR), 1)
#define ProSLIC_DestroyPSTNCheckObj ProSLIC_DestroyPSTNCheckObjs
Destroys a PSTN check object and deallocates memory.
#define ProSLIC_DestroyDiffPSTNCheckObj ProSLIC_DestroyDiffPSTNCheckObjs
Destroys a differential PSTN check object and deallocates memory.
Typedefs
typedef proslicPSTNCheckObjType * proslicPSTNCheckObjType_ptr
typedef proslicDiffPSTNCheckObjType * proslicDiffPSTNCheckObjType_ptr
Enumerations
enum { FEMF_MEAS_DISABLE, FEMF_MEAS_ENABLE }
Functions
int ProSLIC_CreatePSTNCheckObjs (proslicPSTNCheckObjType_ptr *pstnCheckObj, unsigned int num_objs)
Allocates memory for a PSTN check object. One channel object is needed per ProSLIC channel.
int ProSLIC_CreateDiffPSTNCheckObjs (proslicDiffPSTNCheckObjType_ptr *pstnCheckObj, unsigned int num_objs)
Allocates memory for a differential PSTN check object. One channel object is needed per ProSLIC channel.
int ProSLIC_DestroyPSTNCheckObjs (proslicPSTNCheckObjType_ptr *pstnCheckObj)
int ProSLIC_DestroyDiffPSTNCheckObjs (proslicDiffPSTNCheckObjType_ptr *pstnCheckObj)
int ProSLIC_InitPSTNCheckObj (proslicPSTNCheckObjType_ptr pstnCheckObj, int32 avgThresh, int32 singleThresh, uInt8 samples)
Initialize pstnCheckObj structure members.
int ProSLIC_InitDiffPSTNCheckObj (proslicDiffPSTNCheckObjType_ptr pstnDiffCheckObj, int preset1, int preset2, int entry_preset, int femf_enable)
This function initializes a differential PSTN detection object.
int ProSLIC_PSTNCheck (proslicChanType *pProslic, proslicPSTNCheckObjType *pPSTNCheck)
This function monitors longitudinal current (average and single sample) to quickly identify the presence of a live PSTN line. Sufficient polling needs to occur in order to quickly determine if a PSTN line is preset or not.
int ProSLIC_DiffPSTNCheck (proslicChanType *pProslic, proslicDiffPSTNCheckObjType *pPSTNCheck)
This function monitors for a foreign voltage (if enabled) and measures the differential I/V characteristics of the loop at 2 unique settings to detect a foreign PSTN. It is assumed that polling will occur at the configured value found in PSTN_DET_POLL_RATE.
Detailed Description
Monitor for excessive longitudinal current, which would be present if a live pstn line was connected to the port. To operate these sets of functions:
Iniitalize the PSTN object by calling ProSLIC_InitPSTNCheckObj
Poll at a constant rate and call ProSLIC_PSTNCheck. Check the return code of this function.
Alternatively, you can call the DiffPSTNCheck versions of the above two functions.
Note
These functions may be disabled by doing a undef of PSTN_DET_ENABLE in the configuration file.
Macro Definition Documentation
#define MAX_ILONG_SAMPLES 32
How many samples to collect for PSTN check
Definition at line 742 of file proslic.h.
#define MAX_PSTN_SAMPLES 16
Used in the PSTN check status code to indicate the number of samples to collect
Definition at line 743 of file proslic.h.
#define ProSLIC_DestroyDiffPSTNCheckObj ProSLIC_DestroyDiffPSTNCheckObjs
Destroys a differential PSTN check object and deallocates memory.
Parameters
[in] pstnCheckObj - object to deallocate.
Return values
0 = OK
Definition at line 2274 of file proslic.h.
#define ProSLIC_DestroyPSTNCheckObj ProSLIC_DestroyPSTNCheckObjs
Destroys a PSTN check object and deallocates memory.
Parameters
[in] pstnCheckObj - object to deallocate.
Return values
0 = OK
Definition at line 2262 of file proslic.h.
Enumeration Type Documentation
anonymous enum
FEMF OPEN voltage test enable
Enumerator
FEMF_MEAS_DISABLE
Do not measure FEMF as part of PSTN Check
FEMF_MEAS_ENABLE
Do measure FEMF as part of PSTN Check
Definition at line 748 of file proslic.h.
Function Documentation
int ProSLIC_CreateDiffPSTNCheckObjs (proslicDiffPSTNCheckObjType_ptr * pstnCheckObj, unsigned int num_objs)
Allocates memory for a differential PSTN check object. One channel object is needed per ProSLIC channel.
Parameters
[in,out] pstnCheckObj - pointer to the object that is to be initialized.
[in] num_objs - number of objects to allocate
Return values
0 = OK
Referenced by ProSLIC_CreatePSTNCheckObjs().
int ProSLIC_CreatePSTNCheckObjs (proslicPSTNCheckObjType_ptr * pstnCheckObj, unsigned int num_objs)
Allocates memory for a PSTN check object. One channel object is needed per ProSLIC channel.
Parameters
[in,out] pstnCheckObj - pointer to the object that is to be initialized.
[in] num_objs - number of objects to allocate
Return values
0 = OK
Definition at line 3925 of file proslic.c.
References ProSLIC_CreateDiffPSTNCheckObjs(), RC_NO_MEM, RC_NONE, and RC_UNSUPPORTED_FEATURE.
int ProSLIC_DiffPSTNCheck (proslicChanType * pProslic, proslicDiffPSTNCheckObjType * pPSTNCheck)
This function monitors for a foreign voltage (if enabled) and measures the differential I/V characteristics of the loop at 2 unique settings to detect a foreign PSTN. It is assumed that polling will occur at the configured value found in PSTN_DET_POLL_RATE.
Parameters
[in] pProslic - channel to be monitored
[in,out] pPSTNCheck - pointer to an initialized structure that is used by the function to store state information.
Return values
int RC_NONE - test is in progress, RC_COMPLETE_NO_ERR - test complete, no errors, RC_PSTN_OPEN_FEMF - detected foreign voltage, RC_CHANNEL_TYPE_ERR = a non-ProSLIC device was called to perform this function
Referenced by ProSLIC_PSTNCheck().
int ProSLIC_InitDiffPSTNCheckObj (proslicDiffPSTNCheckObjType_ptr pstnDiffCheckObj, int preset1, int preset2, int entry_preset, int femf_enable)
This function initializes a differential PSTN detection object.
Parameters
[in,out] pstnDiffCheckObj - object to be initialized
[in] preset1 - DC Feed preset to be used for first loop I/V measurement
[in] preset2 - DC Feed preset to be used for second loop I/V measurement
[in] entry_preset - restore_preset DC Feed preset that is restored after PSTN check is complete.
[in] femf_enable - Flag to enable OPEN state hazardous voltage measurement (0 = disabled, 1 = enabled)
Return values
0 = OK
Referenced by ProSLIC_InitPSTNCheckObj().
int ProSLIC_InitPSTNCheckObj (proslicPSTNCheckObjType_ptr pstnCheckObj, int32 avgThresh, int32 singleThresh, uInt8 samples)
Initialize pstnCheckObj structure members.
Parameters
[in] pstnCheckObj - which object to initialize
[in] avgThresh - Average current threshold that indicates a PSTN is present (uA).
[in] singleThresh - Single current threshold that indicates a PSTN is present (uA).
[in] samples - number of samples to collect
Return values
0 = OK
Definition at line 4052 of file proslic.c.
References ProSLIC_InitDiffPSTNCheckObj(), PSTN_DET_DIFF_SAMPLES, PSTN_DET_MAX_FEMF, RC_NONE, proslicTestStateType::sampleIterations, proslicTestStateType::stage, and proslicTestStateType::waitIterations.
int ProSLIC_PSTNCheck (proslicChanType * pProslic, proslicPSTNCheckObjType * pPSTNCheck)
This function monitors longitudinal current (average and single sample) to quickly identify the presence of a live PSTN line. Sufficient polling needs to occur in order to quickly determine if a PSTN line is preset or not.
Parameters
[in] pProslic - which channel to run this test on.
[in] pPSTNCheck - the initialized data structure that contains the intermediate results of this test.
Return values
0 = no PSTN detected/thresholds have not been exceeded, 1 = PSTN detected, state machine reset.
Note
If wanting to restart the test, one will need to call ProSLIC_InitPSTNCheckObj again. However, if the number of samples exceeds the buffer then the function will "wrap".
Definition at line 3792 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, ProSLIC_DiffPSTNCheck(), and RC_COMPLETE_NO_ERR.
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page