ProSLIC API: General configuration
General configuration
ProSLIC API
Modules
Debug
Enable/disable channels (for init)
GPIO Control
Patch management.
Data Structures
struct ProslicRegInit
struct ProslicRAMInit
struct proslicPatch
Macros
#define PROSLIC_BCAST_RESET 0x8000
Implement soft reset. For dual channel devices, you can specify a hard reset (which impacts both channels) or if the channel is actually the second channel. The default is to do a soft reset on the 1st channel.
#define PROSLIC_HARD_RESET 3
#define PROSLIC_SOFT_RESET_SECOND_CHAN 2
#define PROSLIC_SOFT_RESET 1
Functions
int ProSLIC_Init_MultiBOM (proslicChanType_ptr *hProslic, int size, int preset)
Loads patch and initializes all ProSLIC devices. Performs all calibrations except longitudinal balance.
int ProSLIC_Init (proslicChanType_ptr *hProslic, int size)
Loads patch and initializes all ProSLIC devices. Performs all calibrations except longitudinal balance.
int ProSLIC_Init_with_Options (proslicChanType_ptr *hProslic, int size, int option)
Loads patch and initializes all ProSLIC devices.
int ProSLIC_Reinit (proslicChanType_ptr *hProslic, int size)
Performs soft reset then calls ProSLIC_Init()
int ProSLIC_LoadRegTable (proslicChanType *pProslic, const ProslicRAMInit *pRamTable, const ProslicRegInit *pRegTable, int bcast)
Loads registers and RAM in the ProSLICs specified.
int ProSLIC_LoadRegTables (proslicChanType_ptr *pProslic, const ProslicRAMInit *pRamTable, const ProslicRegInit *pRegTable, int size)
Loads registers and RAM in the ProSLICs specified.
int ProSLIC_SoftReset (proslicChanType_ptr hProslic, uInt16 resetOptions)
int ProSLIC_ZsynthSetup (proslicChanType_ptr hProslic, int preset)
Configure impedance synthesis.
int ProSLIC_GciCISetup (proslicChanType_ptr hProslic, int preset)
This function configures the CI bits (GCI mode)
Detailed Description
Macro Definition Documentation
#define PROSLIC_BCAST_RESET 0x8000
Implement soft reset. For dual channel devices, you can specify a hard reset (which impacts both channels) or if the channel is actually the second channel. The default is to do a soft reset on the 1st channel.
Parameters
[in] hProslic - which channel to reset
[in] resetOptions - PROSLIC_HARD_RESET (dual channel devices ONLY) | PROSLIC_SOFT_RESET_SECOND_CHAN (dual channel devices) | PROSLIC_BCAST_RESET | PROSLIC_SOFT_RESET
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
Will abort reset if in free run mode.
Only perform a soft reset on 1 channel at a time.
Definition at line 919 of file proslic.h.
Referenced by ProSLIC_LoadRegTables().
Function Documentation
int ProSLIC_GciCISetup (proslicChanType_ptr hProslic, int preset)
This function configures the CI bits (GCI mode)
Parameters
[in] hProslic - which channel to configure
[in] preset - which GCI preset to use from the constants file
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
This function can be disabled by DISABLE_CI_SETUP
Definition at line 1237 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, and RC_COMPLETE_NO_ERR.
int ProSLIC_Init (proslicChanType_ptr * hProslic, int size)
Loads patch and initializes all ProSLIC devices. Performs all calibrations except longitudinal balance.
Parameters
[in] hProslic - which channel(s) to initialize, if size > 1, then the start of the array of channels to be initialized.
[in] size - the number of channels to initialize.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 424 of file proslic.c.
References INIT_NO_OPT, and ProSLIC_Init_with_Options().
int ProSLIC_Init_MultiBOM (proslicChanType_ptr * hProslic, int size, int preset)
Loads patch and initializes all ProSLIC devices. Performs all calibrations except longitudinal balance.
Parameters
[in] hProslic - which channel(s) to initialize, if size > 1, then the start of the array of channels to be initialized.
[in] size - the number of channels to initialize.
[in] preset - general configuration preset to apply
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
ProSLIC_Init
Referenced by ProSLIC_VerifyControlInterface().
int ProSLIC_Init_with_Options (proslicChanType_ptr * hProslic, int size, int option)
Loads patch and initializes all ProSLIC devices.
Parameters
[in] hProslic - which channel(s) to initialize, if size > 1, then the start of the array of channels to be initialized.
[in] size - the number of channels to initialize.
[in] option - see initOptionsType
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 438 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceDeviceType::chipRev, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, proslicPatch::patchData, proslicPatch::patchEntries, ProSLIC_SetUserMode(), proslicPatch::psRamAddr, proslicPatch::psRamData, RC_NONE, SI3218X, SI3219X, SI3226X, and SI3228X.
Referenced by ProSLIC_Init(), and ProSLIC_Reinit().
int ProSLIC_LoadRegTable (proslicChanType * pProslic, const ProslicRAMInit * pRamTable, const ProslicRegInit * pRegTable, int bcast)
Loads registers and RAM in the ProSLICs specified.
Parameters
[in] pProslic - array of channels
[in] pRamTable - array of RAM locations and values to write
[in] pRegTable - array of register locations and values to write
[in] bcast- is broadcast enabled.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
This function should NOT be used since it can bypass the standard initialization/operational state of the ProSLIC.
Definition at line 4277 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelType, PROSLIC, and RC_NONE.
Referenced by ProSLIC_LoadRegTables().
int ProSLIC_LoadRegTables (proslicChanType_ptr * pProslic, const ProslicRAMInit * pRamTable, const ProslicRegInit * pRegTable, int size)
Loads registers and RAM in the ProSLICs specified.
Parameters
[in] pProslic - array of channels
[in] pRamTable - array of RAM locations and values to write
[in] pRegTable - array of register locations and values to write
[in] size - number of ProSLICS to write to.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
This function should NOT be used since it can bypass the standard initialization/operational state of the ProSLIC.
Definition at line 4332 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelEnable, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, SiVoiceChanType::error, INIT_REINIT, PROSLIC, PROSLIC_BCAST_RESET, ProSLIC_LoadRegTable(), ProSLIC_PowerDownConverter(), PSTN_DET_POLL_RATE, RC_CHANNEL_TYPE_ERR, RC_NONE, RC_PLL_FREERUN_ACTIVE, RC_UNSUPPORTED_FEATURE, SiVoiceChanType::scratch, proslicTestStateType::stage, and proslicTestStateType::waitIterations.
int ProSLIC_Reinit (proslicChanType_ptr * hProslic, int size)
Performs soft reset then calls ProSLIC_Init()
Parameters
[in] hProslic - which channel(s) to re-initialize. of channels to be initialized.
[in] size - the number of channels to initialize.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 431 of file proslic.c.
References INIT_REINIT, and ProSLIC_Init_with_Options().
int ProSLIC_ZsynthSetup (proslicChanType_ptr hProslic, int preset)
Configure impedance synthesis.
Parameters
[in] hProslic - which channel to configure
[in] preset - which impedance configuration to load from the constants file.
Return values
int - error from errorCodeType RC_NONE indicates no error.
Note
This function can be disabled by DISABLE_ZSYNTH_SETUP
Definition at line 1182 of file proslic.c.
References SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, PROSLIC, and RC_COMPLETE_NO_ERR.
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page