ProSLIC API: Line Feed status
Line Feed status
ProSLIC API » Signaling - ring & line state, and hook state
Enumerations
enum { POLREV_STOP, POLREV_START, WINK_START, WINK_STOP }
enum {
LF_OPEN, LF_FWD_ACTIVE, LF_FWD_OHT, LF_TIP_OPEN,
LF_RINGING, LF_REV_ACTIVE, LF_REV_OHT, LF_RING_OPEN
}
Functions
int ProSLIC_SetLinefeedStatus (proslicChanType_ptr hProslic, uInt8 newLinefeed)
This function sets the linefeed state.
int ProSLIC_SetLinefeedStatusBroadcast (proslicChanType_ptr hProslic, uInt8 newLinefeed)
This function sets the linefeed state for all channels on the same daisychain.
int ProSLIC_PolRev (proslicChanType_ptr hProslic, uInt8 abrupt, uInt8 newPolRevState)
This function sets the polarity/wink state of the channel.
Detailed Description
Enumeration Type Documentation
anonymous enum
enumeration of the Proslic polarity reversal states - used by ProSLIC_PolRev API
Enumerator
POLREV_STOP
Stop Polarity reversal
POLREV_START
Start Polarity reversal
WINK_START
Start Wink
WINK_STOP
Stop Wink
Definition at line 516 of file proslic.h.
anonymous enum
Defines initialization data structures Linefeed states - used in ProSLIC_SetLinefeedStatus and ProSLIC_SetLinefeedStatusBroadcast
Enumerator
LF_OPEN
Open circuit
LF_FWD_ACTIVE
Forward active
LF_FWD_OHT
Forward active, onhook transmission (used for CID/VMWI)
LF_TIP_OPEN
Tip open
LF_RINGING
Ringing
LF_REV_ACTIVE
Reverse battery/polarity reversed, active
LF_REV_OHT
Reverse battery/polarity reversed, active, onhook transmission (used for CID/VMWI)
LF_RING_OPEN
Ring open
Definition at line 528 of file proslic.h.
Function Documentation
int ProSLIC_PolRev (proslicChanType_ptr hProslic, uInt8 abrupt, uInt8 newPolRevState)
This function sets the polarity/wink state of the channel.
Parameters
[in] hProslic - which channel to modify
[in] abrupt - to change the state immediately
[in] newPolRevState - new polarity state - examples: POLREV_STOP, POLREV_START and WINK_START
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 2140 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelType, POLREV_START, POLREV_STOP, PROSLIC, ProSLIC_SetPowersaveMode(), PWRSAVE_DISABLE, RC_NONE, WINK_START, and WINK_STOP.
int ProSLIC_SetLinefeedStatus (proslicChanType_ptr hProslic, uInt8 newLinefeed)
This function sets the linefeed state.
Parameters
[in] hProslic - which channel to modify
[in] newLinefeed - new line feed state - examples: LF_OPEN, LF_FWD_ACTIVE
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 2013 of file proslic.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelType, SiVoiceDeviceType::chipType, SiVoiceChanType::deviceId, LF_RINGING, PROSLIC, and RC_NONE.
Referenced by ProSLIC_destroyTestInObjs(), ProSLIC_GPIOControl(), ProSLIC_LBCal(), ProSLIC_RingStart(), ProSLIC_RingStop(), and ProSLIC_testLoadTest().
int ProSLIC_SetLinefeedStatusBroadcast (proslicChanType_ptr hProslic, uInt8 newLinefeed)
This function sets the linefeed state for all channels on the same daisychain.
Parameters
[in] hProslic - which channel to modify
[in] newLinefeed - new line feed state - examples: LF_OPEN, LF_FWD_ACTIVE
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 2126 of file proslic.c.
References SiVoiceChanType::channelType, PROSLIC, and RC_COMPLETE_NO_ERR.
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page