ProSLIC API: Diagnostics
Diagnostics
VDAA API
Functions
int Vdaa_ReadLinefeedStatus (vdaaChanType *pVdaa, int8 *vloop, int16 *iloop)
This function returns the Voice DAA linefeed status.
int Vdaa_InitLineInUseCheck (vdaa_LIU_Config *liuCfg, int8 minOnV, int8 minOffV, int16 minOffI)
This function initializes the vdaa_LIU_Config datastructure for line in use feature.
uInt8 Vdaa_CheckForLineInUse (vdaaChanType *pVdaa, vdaa_LIU_Config *liuCfg)
Monitor LVCS to detect intrusion or parallel handset.
int Vdaa_ReadFDTStatus (vdaaChanType_ptr pVdaa)
This function returns the status of the Frame Detect (FDT) bit.
Detailed Description
Function Documentation
uInt8 Vdaa_CheckForLineInUse (vdaaChanType * pVdaa, vdaa_LIU_Config * liuCfg)
Monitor LVCS to detect intrusion or parallel handset.
Parameters
[in] pVdaa - Pointer to Voice DAA channel structure
[in,out] liuCfg - Pointer to vdaa_LIU_Config structure
Return values
VDAA_ONHOOK or VDAA_OFFHOOK (in use)
See also
Vdaa_InitLineInUseCheck
Definition at line 1312 of file vdaa.c.
References SiVoiceChanType::channelType, DAA, Vdaa_GetHookStatus(), and Vdaa_ReadLinefeedStatus().
int Vdaa_InitLineInUseCheck (vdaa_LIU_Config * liuCfg, int8 minOnV, int8 minOffV, int16 minOffI)
This function initializes the vdaa_LIU_Config datastructure for line in use feature.
Parameters
[in,out] liuCfg - Pointer to vdaa_LIU_Config structure (user allocates)
[in] minOnV - minimum onhook loop voltage that indicates no parallel handset is present (V)
[in] minOffV - minimum offhook loop voltage that indicates no parallel handset is present (V)
[in] minOffI - minimum offhook loop current that indicates no parallel handset is preset (mA)
Return values
int - error from errorCodeType RC_NONE indicates no error.
See also
Vdaa_CheckForLineInUse
Definition at line 1282 of file vdaa.c.
References RC_NONE.
int Vdaa_ReadFDTStatus (vdaaChanType_ptr pVdaa)
This function returns the status of the Frame Detect (FDT) bit.
Parameters
[in] pVdaa - Pointer to Voice DAA channel structure
Return values
int - 0 - Frame NOT detected, 1 = Frame detected
Definition at line 1188 of file vdaa.c.
References SiVoiceChanType::channel.
int Vdaa_ReadLinefeedStatus (vdaaChanType * pVdaa, int8 * vloop, int16 * iloop)
This function returns the Voice DAA linefeed status.
Parameters
[in] pVdaa - Pointer to Voice DAA channel structure
[in,out] vloop - Pointer to loop voltage variable (set by this function) - in Volts
[in,out] iloop - Pointer to loop current variable (set by this function) - in mA
Return values
int - error from errorCodeType RC_NONE indicates no error.
Definition at line 752 of file vdaa.c.
References SiVoiceChanType::channel, SiVoiceChanType::channelType, DAA, RC_NONE, and RC_VDAA_ILOOP_OVLD.
Referenced by Vdaa_CheckForLineInUse().
Copyright Fri Apr 20 2018, Silicon Laboratories, ProSLIC API 9.2.0 Released under NDA
Silabs Voice Home page