#!/bin/sh

# This script starts/stops/restarts Qualcomm diag daemon (qdiagd)

PROG_NAME="qdiagd"
PIDFILE="/var/run/$PROG_NAME.pid"

start() {
	echo "qdiag: start $PROG_NAME"
	start-stop-daemon -S -b -m -p $PIDFILE -x "/bin/qdiagd_launcher"
	echo "started."
}

stop() {
	# stop daemon
	echo "qdiag: stop $PROG_NAME"
	start-stop-daemon -K -b -q  -p $PIDFILE 2> /dev/null
	rm -f $PIDFILE

	echo "stopped."
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
