#!/bin/sh -f
#
# Connect script for CDMA modules
#
# This script is called by connection_mgr as follows:-
#
# SCDMA <profile> <instance>
#
# Where:
# <profile> is the configuration profile number to use for this connection
# <instance> is the number of connections using this device
#
PROFILE=$1
INSTANCE=$2


# defines - database variable names
dbVarName_ModuleLock="module.lock"
dbVarName_ModuleLockResult="module.lock_result"
dbVarName_Prefix="wwan.${INSTANCE}."

dbVarName_AtPort="module.at_port"
dbVarName_PPPPort="module.ppp_port"
dbVarName_ModuleName="module.name"
dbVarName_CtrlType="module.control_type"

# defines - binary names
binName_atcmdmgr="atportmgr"

# defines - commands
rdb_get=/usr/bin/rdb_get
rdb_set=/usr/bin/rdb_set
rdb_wait=/usr/bin/rdb_wait

rdbDirectGet() {
	${rdb_get} "$1"
	return $?
}

rdbGet() {
	${rdb_get} "${dbVarName_Prefix}$1"
	return $?
}

rdbDirectSet() {
	${rdb_set} "$1" "$2"
	return $?
}

rdbSet() {
	${rdb_set} "${dbVarName_Prefix}$1" "$2"
	return $?
}

rdbWait() {
	${rdb_wait} "${dbVarName_Prefix}$1" "$2"
	return $?
}

beginWaitLockResult() {
	rdbSet ${dbVarName_ModuleLockResult} "0"
	rdbWait ${dbVarName_ModuleLockResult} 5 &
}

endWaitLockResult() {
	wait $1

	if [ "`rdbGet ${dbVarName_ModuleLockResult}`" == "0" ]; then
		return 1
	fi

	return 0
}

lockorUnlockModule() {

	lockStat=`rdbGet ${dbVarName_ModuleLock}`
	if [ "${lockStat}" == "${1}" ]; then
		return 0
	fi

	# launch subscription in background
	beginWaitLockResult
	WAITPID=$!

	# set lock
	rdbSet ${dbVarName_ModuleLock} ${1}
	
	# wait until done
	logger SCDMA "waiting until atcmdmgr suspened (pid=${WAITPID})"
	if ! endWaitLockResult ${WAITPID}; then
		logger SCDMA "failed to lock database"
		return 1
	fi
	
	logger SCDMA "at command manager suspended"	
	return 0
}


# load environment variables
. `dirname $0`/Env $INSTANCE

# default setting
DEBUG=1
DEFAULTROUTE=""
DNS=1
RETRY=1
GENERIC_MODULE=1

# get tty port
PPP_TTY=`rdbDirectGet "module.ppp_port" || echo /dev/ttyUSB0`
AT_TTY=`rdbDirectGet "module.at_port" || echo /dev/ttyUSB0`

# suspend at command manager if needed
if [ "${PPP_TTY}" == "${AT_TTY}" ]; then
	logger SCDMA "performing database-lock"
	lockorUnlockModule "1"
fi

logger SCDMA "ppp port overridden to ${PPP_TTY}"

# override environemtn variables
TTY=${PPP_TTY}

# enable the profile
rdb_set "link.profile.$PROFILE.enable" 1

# get unit
UNIT=$(( ($PROFILE-1)*4 +$INSTANCE +1 ))

# default cmd
#CMD="pppd unit $UNIT $TTY modem noipdefault nodetach nomppe novj nobsdcomp noaccomp nopcomp nodeflate novj novjccomp ipparam $PROFILE linkname $PROFILE"
# remove noaccomp (no addr/control comp) option
# for accessing cgi.ebay.com.au with ZTE MF-636
CMD="pppd unit $UNIT $TTY modem noipdefault nodetach nomppe novj nobsdcomp nopcomp nodeflate novj novjccomp ipparam $PROFILE linkname $PROFILE"

# build cmd
test "$DEBUG" = "1"		&& CMD="$CMD debug"
test -n "$DEFAULTROUTE"		&& CMD="$CMD defaultroute"
test -n  "$DNS"			&& CMD="$CMD usepeerdns"
test "$WWAN_AUTH_TYPE" = "pap"	&& CMD="$CMD refuse-chap refuse-mschap-v2 refuse-mschap refuse-eap"
test -n "$WWAN_USER"		&& CMD="$CMD user $WWAN_USER"
test -n "$WWAN_PASS"		&& CMD="$CMD password $WWAN_PASS"

if [ "$WWAN_OPMODE" == "OnDemand" ]; then
	CMD="$CMD demand holdoff 10 idle $WWAN_IDLE"
fi

# add ondemand default gateway
. demandgw.sh
connectOnDemand&

# build chat param
DIALCMD="atdt$WWAN_DIALSTR"
APNCMD="AT"

CMD="$CMD connect \"/bin/chat -v -f /etc_ro/ppp/chatscripts/umts -T $DIALCMD -U $APNCMD\" "

# run
logger SCDMA "$CMD"
eval "exec $CMD"
