#!/bin/sh -f
#
# Connect script for Sierra Wireless UMTS modules
#
# This script is called by connection_mgr as follows:-
#
# SSierraUMTS <profile> <instance>
#
# Where:
# <profile> is the configuration profile number to use for this connection
# <instance> is the number of connections using this device
#
PROFILE=$1
INSTANCE=$2


# defines - database variable names
dbVarName_ModuleLock="module.lock"
dbVarName_ModuleLockResult="module.lock_result"
dbVarName_Prefix="wwan.${INSTANCE}."

dbVarName_AtPort="module.at_port"
dbVarName_PPPPort="module.ppp_port"
dbVarName_ModuleName="module.name"
dbVarName_CtrlType="module.control_type"

# defines - binary names
binName_atcmdmgr="atportmgr"

# defines - commands
rdb_get=/usr/bin/rdb_get
rdb_set=/usr/bin/rdb_set
rdb_wait=/usr/bin/rdb_wait

rdbDirectGet() {
	${rdb_get} "$1"
	return $?
}

rdbGet() {
	${rdb_get} "${dbVarName_Prefix}$1"
	return $?
}

rdbDirectSet() {
	${rdb_set} "$1" "$2"
	return $?
}

rdbSet() {
	${rdb_set} "${dbVarName_Prefix}$1" "$2"
	return $?
}

rdbWait() {
	${rdb_wait} "${dbVarName_Prefix}$1" "$2"
	return $?
}

beginWaitLockResult() {
	rdbSet ${dbVarName_ModuleLockResult} "0"
	rdbWait ${dbVarName_ModuleLockResult} 5 &
}

endWaitLockResult() {
	wait $1

	if [ "`rdbGet ${dbVarName_ModuleLockResult}`" == "0" ]; then
		return 1
	fi

	return 0
}

lockorUnlockModule() {

	lockStat=`rdbGet ${dbVarName_ModuleLock}`
	if [ "${lockStat}" == "${1}" ]; then
		return 0
	fi

	# launch subscription in background
	beginWaitLockResult
	WAITPID=$!

	# set lock
	rdbSet ${dbVarName_ModuleLock} ${1}
	
	# wait until done
	logger SIPWL "waiting until atcmdmgr suspened (pid=${WAITPID})"
	if ! endWaitLockResult ${WAITPID}; then
		logger SIPWL "failed to lock database"
		return 1
	fi
	
	logger SIPWL "at command manager suspended"	
	return 0
}


# load environment variables
. `dirname $0`/Env $INSTANCE

# default setting
DEBUG=1
DEFAULTROUTE=""
DNS=1
RETRY=1
GENERIC_MODULE=1

# mtu size
OPT_MTU=""
MTU_SIZE=$(nvram_get wwan_mtu)
test -n "$MTU_SIZE" && OPT_MTU="mtu $MTU_SIZE"

# get tty port
PPP_TTY=`rdbDirectGet "module.ppp_port" || echo /dev/ttyUSB0`
AT_TTY=`rdbDirectGet "module.at_port" || echo /dev/ttyUSB0`


# 

AUTHMODE="$(nvram_get wwan_authmode)"

WWAN_USER="$(nvram_get wwan_user)"
WWAN_PASS="$(nvram_get wwan_pass)"

if [ "$AUTHMODE" == "unpw" ]; then
	WWAN_APN="$(nvram_get wwan_APN)"
else
	WWAN_APN="$(rdb_get wwan.0.profile.cmd.param.apn)"
fi

logger SIPWL "read auth. information ($WWAN_USER/$WWAN_PASS/$WWAN_APN)"

rdb_set wwan_APN "$WWAN_APN"

# suspend at command manager if needed
if [ "${PPP_TTY}" == "${AT_TTY}" ]; then
	logger SIPWL "performing database-lock"
	lockorUnlockModule "1"
fi

logger SIPWL "ppp port overridden to ${PPP_TTY}"

# override environemtn variables
TTY=${PPP_TTY}

# enable the profile
rdb_set "link.profile.$PROFILE.enable" 1

# get unit
UNIT=$(( ($PROFILE-1)*4 +$INSTANCE +1 ))

OPT_USER=""
OPT_PASS=""
test -n "$WWAN_USER" && OPT_USER="user $WWAN_USER"
test -n "$WWAN_PASS" && OPT_PASS="password $WWAN_PASS"

# default cmd
CMD="pppd unit $UNIT $TTY $OPT_USER $OPT_PASS crtscts sync modem noipdefault nodetach ipparam $PROFILE linkname $PROFILE $OPT_MTU"

# build cmd
test "$DEBUG" = "1"		&& CMD="$CMD debug"
test -n "$DEFAULTROUTE"		&& CMD="$CMD defaultroute"
test -n  "$DNS"			&& CMD="$CMD usepeerdns"
test "$WWAN_AUTH_TYPE" = "pap"	&& CMD="$CMD refuse-chap refuse-mschap-v2 refuse-mschap refuse-eap"

if [ "$WWAN_OPMODE" == "OnDemand" ]; then
	CMD="$CMD demand holdoff 10 idle $WWAN_IDLE"
fi


# add ondemand default gateway
. demandgw.sh
connectOnDemand&

# build chat param
DIALCMD="atd$WWAN_DIALSTR"
CMD="$CMD connect \"/bin/chat -v -f /etc_ro/ppp/chatscripts/umts -T $DIALCMD -U AT\" "

# run
logger SIPWL "$CMD"
eval "exec $CMD"
