#!/bin/sh -f
#
# Connect script for Sierra Wireless Packetized modules
#
# This script is called by wwand_deamon as follows:-
#
# SUSBNET <profile> <instance>
#
# Where:
# <profile> is the configuration profile number to use for this connection
# <instance> is the number of connections using this device
#

#
# <action> is only used for internal purpose
#


PROFILE=$1
INSTANCE=$2

BIN=$0
ACTION=$3

test -z "$ACTION" && ACTION=start

log() {
	logger SUSBNET -- $@
}

getUsbNetIp() {
	LINE=`ifconfig usb0 | grep "inet addr"`
	LINE=${LINE##*addr:}
	echo ${LINE%% Bcast*}
}

execWait() {
	timeout=$1
	shift
	eval "$@ &"
	
	pid=$!
	count=0
	while [ -e /proc/$pid ]; do

		count=$(( $count + 1 ))
		if [ $count -gt  $timeout ]; then
			break;
		fi
	
		sleep 1
	done
	
	ret=$?

	if [ -e /proc/$pid ]; then
		kill -9 $pid
		ret=255
	fi

	wait $pid

	return $ret
}


startUsbNet() {
	# enable profile
	rdb_set link.profile.$PROFILE.enable 1

	# load environment variables
	. `dirname $0`/Env $INSTANCE

	OPTUSER=""
	OPTPASS=""
	OPTAUTH=""

	if [ -n "$WWAN_USER" -a -n "$WWAN_PASS" ]; then
		OPTUSER="user $WWAN_USER"
		OPTPASS="password $WWAN_PASS"

		if [ "$WWAN_AUTH_TYPE" = "pap" ]; then
			OPTAUTH="pap"
		else
			OPTAUTH="chap"
		fi
	fi

	log "launching... cns_profile write id 0 apn \"$WWAN_APN\" $OPTAUTH $OPTUSER"
	if ! cns_profile write id 0 apn "$WWAN_APN" $OPTAUTH $OPTUSER $OPTPASS; then
		log "cns communication failed - setting configuration failure"
	fi

	# get the module online	
	log "launching... cns_profile activate"
	if ! cns_profile activate; then
		log "cns communication failed - activation failure"
		return 1
	fi

	# get the interface up
	log "activating... usb0 interface"
	ifconfig usb0 down
	if ! ifconfig usb0 up; then
		log "ifconfig failed - having the interface up"
		return 1
	fi
	
	# get ip address from the driver - fake dhcp server
	log "launching dhcp client udhcpc -f -q -i usb0 -s /sbin/udhcpc.sh"
	if ! execWait 20 "udhcpc -f -q -i usb0 -s /sbin/udhcpc.sh"; then
		log "failed to get ip address in udhcpc"
		return 1
	fi

	#
	# workaround for Sierra usbnet failure - module occaionally hands over an incorrect IP address to the first inqury
	# MC8790V K2.0.7.34BT / K2.0.7.30AP
	#
	log "launching dhcp client udhcpc#2 -f -q -i usb0 -s /sbin/udhcpc.sh"
	if ! execWait 20 "udhcpc -f -q -i usb0 -s /sbin/udhcpc.sh"; then
		log "failed to get ip address in udhcpc"
		return 1
	fi

	log "usbnet connection up"

	# build environment variables for ip-up script 
	PPP_IFACE="usb0"
	PPP_TTY=""
	PPP_SPEED=""
	PPP_LOCAL=`getUsbNetIp`
	PPP_REMOTE="0.0.0.0"
	PPP_IPPARAM="$PROFILE"

	/etc_ro/ppp/ip-up "$PPP_IFACE" "$PPP_TTY" "$PPP_SPEED" "$PPP_LOCAL" "$PPP_REMOTE" "$PPP_IPPARAM"

	log "ip-up script called - ipaddr=$PPP_LOCAL,dev=$PPP_IFACE,profile=$PPP_IPPARAM"
}

stopUsbNet() {
	if ifconfig usb0 > /dev/null 2>&1; then
		# get the module down
		if ! cns_profile deactivate; then
			log "cns communication failed - deactivation failure"
		fi
	
		# get the interface down
		if ! ifconfig usb0 down; then
			log "ifconfig failed - having the interface down"
		fi
	
		log "usbnet connection down"
	fi

	# build environment variables for ip-up script 
	PPP_IFACE="usb0"
	PPP_TTY=""
	PPP_SPEED=""
	PPP_LOCAL=`getUsbNetIp`
	PPP_REMOTE="0.0.0.0"
	PPP_IPPARAM="$PROFILE"

	/etc_ro/ppp/ip-down "$PPP_IFACE" "$PPP_TTY" "$PPP_SPEED" "$PPP_LOCAL" "$PPP_REMOTE" "$PPP_IPPARAM"

	log "ip-down script called - ipaddr=$PPP_LOCAL,dev=$PPP_IFACE,profile=$PPP_IPPARAM"
}



case $ACTION in
	'start')
		# start usb net
		if startUsbNet; then
			# stopusbNet on term signal
			exec runonterm "$BIN $PROFILE $INSTANCE stop"
		fi
		;;

	'stop')
		stopUsbNet;
		;;
esac

