#!/bin/sh

# This script starts/stops/restarts celltrakcing

PROG_NAME="celltracking"
PIDFILE="/var/run/$PROG_NAME.pid"

start() {
	echo "celltracking: start $PROG_NAME"
	start-stop-daemon -S -b -m -p $PIDFILE -x "/usr/bin/celltracking"
	echo "started."
}

stop() {
	# stop daemon
	echo "celltracking: stop $PROG_NAME"
	local PID=$(cat $PIDFILE 2>/dev/null)
	start-stop-daemon -K -q -p $PIDFILE 2> /dev/null
	rm -f $PIDFILE
	echo "stopped."
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit $?
