#ifndef __WWANDAEMON_H__
#define __WWANDAEMON_H__

#define PING_CONSECUTIVE_COUNT	3
#define PING_NSLOOKUP_TIMEOUT		5
#define PING_FREQ	5


#define PING_TO3G_INTENSIVE_COUNT	3

#define PING_TO3G_INTENSIVE_FREQ	1
#define PING_TO3G_NORMAL_FREQ		5
#define PING_TO3G_TOTAL_COUNT		5


#endif
