/* soapStub.h
   Generated by gSOAP 2.7.0f from interop_all.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under one of the following three licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
   See README.txt for further details.
*/
#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"

SOAP_BEGIN_NAMESPACE(soap)

/* Enumerations */

/* Classes and Structs */

/* ns:echoStringResponse: */
struct ns__echoStringResponse
{
	char *_return;	/* RPC return element */	/* required element */
};

/* ns:echoString: */
struct ns__echoString
{
	char *inputString;	/* optional element */
};

/* SOAP encoded array of xsd:string schema type: */
struct ArrayOfstring
{
	char **__ptr;
	int __size;
	int __offset;
};

/* ns:echoStringArrayResponse: */
struct ns__echoStringArrayResponse
{
	struct ArrayOfstring _return;	/* RPC return element */	/* required element */
};

/* ns:echoStringArray: */
struct ns__echoStringArray
{
	struct ArrayOfstring inputStringArray;	/* required element */
};

/* ns:echoIntegerResponse: */
struct ns__echoIntegerResponse
{
	long _return;	/* RPC return element */	/* required element */
};

/* ns:echoInteger: */
struct ns__echoInteger
{
	long inputInteger;	/* required element */
};

/* SOAP encoded array of xsd:int schema type: */
struct ArrayOfint
{
	long **__ptr;
	int __size;
	int __offset;
};

/* ns:echoIntegerArrayResponse: */
struct ns__echoIntegerArrayResponse
{
	struct ArrayOfint _return;	/* RPC return element */	/* required element */
};

/* ns:echoIntegerArray: */
struct ns__echoIntegerArray
{
	struct ArrayOfint inputIntegerArray;	/* required element */
};

/* ns:echoFloatResponse: */
struct ns__echoFloatResponse
{
	float _return;	/* RPC return element */	/* required element */
};

/* ns:echoFloat: */
struct ns__echoFloat
{
	float inputFloat;	/* required element */
};

/* SOAP encoded array of xsd:float schema type: */
struct ArrayOffloat
{
	float **__ptr;
	int __size;
	int __offset;
};

/* ns:echoFloatArrayResponse: */
struct ns__echoFloatArrayResponse
{
	struct ArrayOffloat _return;	/* RPC return element */	/* required element */
};

/* ns:echoFloatArray: */
struct ns__echoFloatArray
{
	struct ArrayOffloat inputFloatArray;	/* required element */
};

/* s:SOAPStruct: */
struct s__SOAPStruct
{
	char *varString;	/* optional element */
	long *varInt;	/* optional element */
	float *varFloat;	/* optional element */
};

/* ns:echoStructResponse: */
struct ns__echoStructResponse
{
	struct s__SOAPStruct _return;	/* RPC return element */	/* required element */
};

/* ns:echoStruct: */
struct ns__echoStruct
{
	struct s__SOAPStruct _inputStruct;	/* required element */
};

/* SOAP encoded array of s:SOAPStruct schema type: */
struct ArrayOfSOAPStruct
{
	struct s__SOAPStruct **__ptr;
	int __size;
	int __offset;
};

/* ns:echoStructArrayResponse: */
struct ns__echoStructArrayResponse
{
	struct ArrayOfSOAPStruct _return;	/* RPC return element */	/* required element */
};

/* ns:echoStructArray: */
struct ns__echoStructArray
{
	struct ArrayOfSOAPStruct inputStructArray;	/* required element */
};

/* ns:echoVoidResponse: */
struct ns__echoVoidResponse
{
};

/* ns:echoVoid: */
struct ns__echoVoid
{
};

/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
};

/* ns:echoBase64Response: */
struct ns__echoBase64Response
{
	struct xsd__base64Binary _return;	/* RPC return element */	/* required element */
};

/* ns:echoBase64: */
struct ns__echoBase64
{
	struct xsd__base64Binary inputBase64;	/* required element */
};

/* ns:echoDateResponse: */
struct ns__echoDateResponse
{
	char *_return;	/* RPC return element */	/* required element */
};

/* ns:echoDate: */
struct ns__echoDate
{
	char *inputDate;	/* optional element */
};

/* hexBinary schema type: */
struct xsd__hexBinary
{
	unsigned char *__ptr;
	int __size;
};

/* ns:echoHexBinaryResponse: */
struct ns__echoHexBinaryResponse
{
	struct xsd__hexBinary _return;	/* RPC return element */	/* required element */
};

/* ns:echoHexBinary: */
struct ns__echoHexBinary
{
	struct xsd__hexBinary inputHexBinary;	/* required element */
};

/* ns:echoDecimalResponse: */
struct ns__echoDecimalResponse
{
	char *_return;	/* RPC return element */	/* required element */
};

/* ns:echoDecimal: */
struct ns__echoDecimal
{
	char *inputDecimal;	/* optional element */
};

/* ns:echoBooleanResponse: */
struct ns__echoBooleanResponse
{
	bool _return;	/* RPC return element */	/* required element */
};

/* ns:echoBoolean: */
struct ns__echoBoolean
{
	bool inputBoolean;	/* required element */
};

/* ns:echoStructAsSimpleTypesResponse: */
struct ns__echoStructAsSimpleTypesResponse
{
	char *_outputString;	/* RPC return element */	/* optional element */
	long *_outputInteger;	/* optional element */
	float *_outputFloat;	/* optional element */
};

/* ns:echoStructAsSimpleTypes: */
struct ns__echoStructAsSimpleTypes
{
	struct s__SOAPStruct _inputStruct;	/* required element */
};

/* ns:echoSimpleTypesAsStructResponse: */
struct ns__echoSimpleTypesAsStructResponse
{
	struct s__SOAPStruct _return;	/* RPC return element */	/* required element */
};

/* ns:echoSimpleTypesAsStruct: */
struct ns__echoSimpleTypesAsStruct
{
	char *inputString;	/* optional element */
	long *inputInteger;	/* optional element */
	float *inputFloat;	/* optional element */
};

/* SOAP encoded array of xsd:string schema type: */
struct ArrayOfstring2D
{
	char **__ptr;
	int __size[2];
	int __offset[2];
};

/* ns:echo2DStringArrayResponse: */
struct ns__echo2DStringArrayResponse
{
	struct ArrayOfstring2D _return;	/* RPC return element */	/* required element */
};

/* ns:echo2DStringArray: */
struct ns__echo2DStringArray
{
	struct ArrayOfstring2D _input2DStringArray;	/* required element */
};

/* s:SOAPStructStruct: */
struct s__SOAPStructStruct
{
	char *varString;	/* optional element */
	long *varInt;	/* optional element */
	float *varFloat;	/* optional element */
	struct s__SOAPStruct *varStruct;	/* optional element */
};

/* ns:echoNestedStructResponse: */
struct ns__echoNestedStructResponse
{
	struct s__SOAPStructStruct _return;	/* RPC return element */	/* required element */
};

/* ns:echoNestedStruct: */
struct ns__echoNestedStruct
{
	struct s__SOAPStructStruct _inputStruct;	/* required element */
};

/* s:SOAPArrayStruct: */
struct s__SOAPArrayStruct
{
	char *varString;	/* optional element */
	long *varInt;	/* optional element */
	float *varFloat;	/* optional element */
	struct ArrayOfstring varArray;	/* required element */
};

/* ns:echoNestedArrayResponse: */
struct ns__echoNestedArrayResponse
{
	struct s__SOAPArrayStruct _return;	/* RPC return element */	/* required element */
};

/* ns:echoNestedArray: */
struct ns__echoNestedArray
{
	struct s__SOAPArrayStruct _inputStruct;	/* required element */
};

/* SOAP Header: */
struct SOAP_ENV__Header
{
	char *h__echoMeStringRequest;	/* optional element */
	char *h__echoMeStringRequest_;	/* mustUnderstand */
	char *h__echoMeStringResponse;	/* optional element */
	struct s__SOAPStruct *h__echoMeStructRequest;	/* optional element */
	struct s__SOAPStruct *h__echoMeStructRequest_;	/* mustUnderstand */
	struct s__SOAPStruct *h__echoMeStructResponse;	/* optional element */
	char *h__someUnknownRequest;	/* optional element */
	char *h__someUnknownRequest_;	/* mustUnderstand */
};

/* m:echoVoidResponse: */
struct m__echoVoidResponse
{
};

/* m:echoVoid: */
struct m__echoVoid
{
};

/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element */
	char *SOAP_ENV__Node;	/* optional element */
	char *SOAP_ENV__Role;	/* optional element */
};

/* SOAP-ENV:Detail: */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};

/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element */
	char *faultstring;	/* optional element */
	char *faultactor;	/* optional element */
	struct SOAP_ENV__Detail *detail;	/* optional element */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element */
	char *SOAP_ENV__Reason;	/* optional element */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element */
};

/* Types With Custom (De)serializers: */

/* Typedefs */
typedef char *_XML;
typedef char *_QName;
typedef char *xsd__string;
typedef long xsd__int;
typedef float xsd__float;
typedef char *xsd__dateTime;
typedef char *xsd__decimal;
typedef bool xsd__boolean;

/* Extern */

/* Remote Methods */

SOAP_FMAC5 int SOAP_FMAC6 ns__echoString(struct soap*, char *, char *&);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoStringArray(struct soap*, struct ArrayOfstring, struct ArrayOfstring &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoInteger(struct soap*, long, long &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoIntegerArray(struct soap*, struct ArrayOfint, struct ArrayOfint &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoFloat(struct soap*, float, float &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoFloatArray(struct soap*, struct ArrayOffloat, struct ArrayOffloat &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoStruct(struct soap*, struct s__SOAPStruct, struct ns__echoStructResponse &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoStructArray(struct soap*, struct ArrayOfSOAPStruct, struct ArrayOfSOAPStruct &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoVoid(struct soap*, struct ns__echoVoidResponse &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoBase64(struct soap*, struct xsd__base64Binary, struct xsd__base64Binary &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoDate(struct soap*, char *, char *&);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoHexBinary(struct soap*, struct xsd__hexBinary, struct xsd__hexBinary &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoDecimal(struct soap*, char *, char *&);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoBoolean(struct soap*, bool, bool &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoStructAsSimpleTypes(struct soap*, struct s__SOAPStruct, struct ns__echoStructAsSimpleTypesResponse &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoSimpleTypesAsStruct(struct soap*, char *, long *, float *, struct ns__echoSimpleTypesAsStructResponse &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echo2DStringArray(struct soap*, struct ArrayOfstring2D, struct ArrayOfstring2D &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoNestedStruct(struct soap*, struct s__SOAPStructStruct, struct ns__echoNestedStructResponse &);

SOAP_FMAC5 int SOAP_FMAC6 ns__echoNestedArray(struct soap*, struct s__SOAPArrayStruct, struct ns__echoNestedArrayResponse &);

SOAP_FMAC5 int SOAP_FMAC6 m__echoVoid(struct soap*, struct m__echoVoidResponse &);

/* Stubs */

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoString(struct soap*, const char*, const char*, char *, char *&);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoStringArray(struct soap*, const char*, const char*, struct ArrayOfstring, struct ArrayOfstring &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoInteger(struct soap*, const char*, const char*, long, long &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoIntegerArray(struct soap*, const char*, const char*, struct ArrayOfint, struct ArrayOfint &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoFloat(struct soap*, const char*, const char*, float, float &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoFloatArray(struct soap*, const char*, const char*, struct ArrayOffloat, struct ArrayOffloat &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoStruct(struct soap*, const char*, const char*, struct s__SOAPStruct, struct ns__echoStructResponse &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoStructArray(struct soap*, const char*, const char*, struct ArrayOfSOAPStruct, struct ArrayOfSOAPStruct &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoVoid(struct soap*, const char*, const char*, struct ns__echoVoidResponse &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoBase64(struct soap*, const char*, const char*, struct xsd__base64Binary, struct xsd__base64Binary &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoDate(struct soap*, const char*, const char*, char *, char *&);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoHexBinary(struct soap*, const char*, const char*, struct xsd__hexBinary, struct xsd__hexBinary &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoDecimal(struct soap*, const char*, const char*, char *, char *&);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoBoolean(struct soap*, const char*, const char*, bool, bool &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoStructAsSimpleTypes(struct soap*, const char*, const char*, struct s__SOAPStruct, struct ns__echoStructAsSimpleTypesResponse &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoSimpleTypesAsStruct(struct soap*, const char*, const char*, char *, long *, float *, struct ns__echoSimpleTypesAsStructResponse &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echo2DStringArray(struct soap*, const char*, const char*, struct ArrayOfstring2D, struct ArrayOfstring2D &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoNestedStruct(struct soap*, const char*, const char*, struct s__SOAPStructStruct, struct ns__echoNestedStructResponse &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__echoNestedArray(struct soap*, const char*, const char*, struct s__SOAPArrayStruct, struct ns__echoNestedArrayResponse &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_m__echoVoid(struct soap*, const char*, const char*, struct m__echoVoidResponse &);

/* Skeletons */

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoString(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoStringArray(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoInteger(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoIntegerArray(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoFloat(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoFloatArray(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoStruct(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoStructArray(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoVoid(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoBase64(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoDate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoHexBinary(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoDecimal(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoBoolean(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoStructAsSimpleTypes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoSimpleTypesAsStruct(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echo2DStringArray(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoNestedStruct(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__echoNestedArray(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_m__echoVoid(struct soap*);

SOAP_END_NAMESPACE(soap)

#endif

/* end of soapStub.h */
