#!/usr/bin/awk -f

function exec(mycmd) {
value="";
	while(mycmd | getline) {
		value = sprintf("%s%s", value, $0);
	}
	close(mycmd);
	return value;
}

function get_enabled () {
	x=0;
	for( i=1; i<=6; i++) {
		y=exec("rdb_get link.profile."i".enable");
		if(y=="1") {
			x++;
		}
	}
	return x;
}

BEGIN {

	if( ARGC>=2 && ARGV[1]=="help" ) {
		print "This AWK script is used by SMS tools for controlling"
		print "the default profile."
		print "WARNING: Using this command may cause loss of network connectivity, and may ruin internal system state."
        print "This command takes 1 parameter:"
        print "get - returns the index of the current default profile"
        print "set - take one additional parameter (a profile index, 1-6),"
        print "      and sets the default profile to this index."
		exit (0);
	}

	if( ARGC < 2 || (ARGV[1]=="set" && (ARGV[2]<1 || ARGV[2]>6)) ) {
		print "Parameter ERROR:" ARGC;
		exit (0);
	}
	current_default_profile=1;
	for(i=1; i<=6; i++) {
		def_route=exec("rdb_get link.profile."i".defaultroute" );
		if(def_route=="1") {
			current_default_profile=i;
			break;
		}
	}
	if ( ARGV[1]=="set" ) {
		maxpdp=exec("rdb_get wwan.0.max_sub_if");
		if (maxpdp=="") {
			maxpdp=2;
		}

		s=exec("rdb_get link.profile."ARGV[2]".enable");
		if( get_enabled()>maxpdp || (get_enabled()==maxpdp && s!="1" ) ) {
			exec( "rdb_set link.profile."current_default_profile".enable 0");
		}
		if(current_default_profile!=ARGV[2]) {
			exec( "rdb_set link.profile."current_default_profile".defaultroute 0");
			exec("rdb_set link.profile."ARGV[2]".defaultroute 1");
		}
		exec("rdb_set link.profile."ARGV[2]".enable 1");
		msg="Default Profile="ARGV[2];
	}
	else if ( ARGV[1]=="get" ) {
		msg="Default Profile="current_default_profile;
	}
	else {
		print "Parameter ERROR:" ARGC;
		exit (0);
	}
	system( "logger '"msg"'" );
	print msg;
}
